"""E240 — FQ8, THE MOMENT ARCHIVE (T215's "the wind has memory" made
observational; design frozen in scratch/e240_design.md BEFORE this script;
dispatched 2026-10-04).

THE QUESTION: does Adam's optimizer state retain the eaten facts'
directions after the weights have forgotten them? Reconstruct m_t, v_t
over the certified wash gradients (the wash's exact hyperparameters);
read the applied direction d_t = m_hat/sqrt(v_hat) against the 54 t=0
supports — killed vs living (z vs the cross-probe null).

BARS VERBATIM (frozen in scratch/e240_design.md at dispatch; registered
in the dispatch brief; adjudicate against exactly this; no bar shopping):
  - H-FOSSIL — "the killed probes' supports are overrepresented in the
    applied direction at +80 (contrast z >= 2, sustained over the last 20
    steps) — the moments remember what the weights forgot; the no-archive
    law's amendment candidate; the intervention leg unlocks"
  - H-TRANSIENT — "the contrast decays on a ~10-20-step scale regardless
    of fate (z < 1 by +40) — the memory is the supply's echo; e237's
    pre-Adam cut is exactly right"
  - NEITHER — "no contrast at any state — the moment substrate is
    fate-blind"
  (The intervention leg — one moment-only step from +80 — is NOT in this
  cell; it unlocks only on H-FOSSIL and dispatches separately.)

REGISTERED PREDICTIONS (verbatim from the dispatch; no retrofit):
  (a) "under H-TRANSIENT the decay timescale matches e179's ~18-step
      stickiness"
  (b) "FQ3 co-read — v_t's implied per-coordinate step scale on the fact
      battery's coordinates vs T139's pace clause"
  (c) "the w2 reconstruction reproduces the w1 story in sign"

OPERATIONALIZATIONS (frozen here BEFORE compute; they fix the clauses,
they do not move the bars):
  * RECONSTRUCTION: the e234 gradient cache's memmaps were DELETED on
    that cell's DONE (its disclosed lifecycle), so the certified
    gradients are REGENERATED by the identical deterministic replay
    (same seeds 18202/20261002/21703, same threads-8 CPU arithmetic,
    certified by G_CE bit-exactness vs e234's journaled CE/gnorms,
    G_DRAWS bit-exact generator states, G_REPLAY drift vs the archived
    checkpoints) and STREAMED into the fp64 AdamW recursions — never
    stored whole (the design's RAM-streaming clause, honored in the
    regeneration form). Moments PRIMARY = over the CLIPPED gradients
    (what the wash's AdamW actually drank — the recipe's clip 1.0 binds
    every step, raw gnorms 3.4-25.7); the RAW-gradient flavor (the
    design's literal "cached gradients" reading) is co-reported as a
    second recursion — it differs only through the clip factor's
    step-to-step variation. Recursion: m = b1*m + (1-b1)*g, v = b2*v +
    (1-b2)*g^2, bias corrections 1-b1^t / 1-b2^t exact, eps 1e-8 INSIDE
    the denominator (torch's form): d_t = (m/b1c)/((v/b2c).sqrt()+eps).
    wd 0.1 acts on the WEIGHTS, not gradients (AdamW decoupling) — d_t
    is the gradient-driven direction; the wd term enters only the
    applied-STEP reconstruction used for validation.
  * APPLIED-STEP VALIDATION (the design's honesty guard, three legs):
    G_STEP — the reconstructed full step -lr*(wd*theta_prev + d_t)
    matches the LIVE optimizer's own step norm per step (machine
    precision); G_MOMENT — the reconstructed m/v match the live
    optimizer's exp_avg/exp_avg_sq elementwise at every archived state;
    G_E233 — the w1 applied-step NORM trajectory matches e233's
    committed C-arm ledger (the independent GPU-fp32 product; disclosed
    precision spans the CPU/GPU texture tier: Spearman >= 0.99, median
    relative deviation <= 2%, max <= 5%).
  * READS at every step (the decay curve needs full resolution): the
    signed alignment a_i(t) = cos(d_t, s_i) per probe (supports are the
    ASCENT directions of p(answer), so a killing displacement -lr*d
    anti-aligns with s_i — killed supports OVERREPRESENTED in d_t reads
    as POSITIVE alignment); the |a| flavor co-reported. The v-mask read
    (v_t's mass on each support's hot set vs its complement) and the
    pace table at the ARCHIVED states {2,10,50,80} (w1) / {10,50,80}
    (w2/w3). Hot set = top-|s_i| coordinates, e226's own 124M ladder:
    k=2000 primary, 20000/200000 co-reported.
  * THE CONTRAST: per (wash, step), killed := p(+80) < 0.5*p(0) (e232's
    standing-zombie belief clause) from e234's committed journal
    trajectories (G_TRAJ-gated extension of e214's records); living :=
    the rest. z(t) = (mean_K - mean_L) / (sd54(t) * sqrt(1/nK + 1/nL))
    — e226's frozen band-sigma convention (the 54's OWN cross-probe
    spread — the g11 shared-hot-set guard: the null is the probes' own
    mutual overlaps, never a random basis) raised to the two-sample
    form; 20000 label permutations co-check the analytic z at states
    {2,10,40,80}. POOLED primary = inverse-variance fixed-effects over
    the three washes; per-wash co-reports; the majority-fate fixed
    grouping co-reported; the 54x54 support-overlap structure
    (within-K / within-L / cross cosines) disclosed alongside.
  * SUPPLY-ECHO REFERENCE (interpretation-critical co-report, no bar
    moved): z_g(t) — the same contrast applied to the CURRENT clipped
    gradient's alignment (the supply). The fossil read is z_d
    OVER AND ABOVE the supply's echo; the registered bars speak on z_d
    alone, this co-report interprets.
  * ADJUDICATION (order H-FOSSIL -> H-TRANSIENT -> NEITHER; pooled
    primary): sustained := z_pool(t) >= 2 at EVERY t in 61..80
    (window-min form; the count of window steps >= 2 co-reported);
    H-TRANSIENT := z_pool(t) < 1 for every t in 40..80 AND an early
    contrast existed (max z_pool(1..39) >= 2); NEITHER := everything
    else. Contingency (disclosed, no bar shopping): an early contrast
    that settles in [1, 2) over 40..80 matches no bar — the verdict
    says NEITHER with the numbers verbatim.
  * PREDICTION (a): the decay timescale read regardless (binding only
    under H-TRANSIENT): the settled crossing t_cross (first t with z < 1
    thereafter) + an exponential half-life fit of the pooled mean-
    difference over t in 1..40, compared to e179's ~18 steps (the
    1/(1-beta2) = 20-step window note attached).
  * PREDICTION (b): the pace table per archived state — mean |d| over
    all coordinates vs over the fact battery's hot coordinates (union
    of the 20 fact probes' top-2000 |s|; ladder co-report), the implied
    displacement lr*||d|| vs the observed live ||Delta|| (T139's clock
    clause), and ||d||/sqrt(N_active) vs 1 (the pace clause's uniform
    sign-step assumption). "Co-moves" := the fact coords' scale tracks
    the global scale with no systematic departure > 10%.
  * PREDICTION (c): w2 vs w1 in sign — the sign of the pooled-late z
    agrees AND >= 2/3 of shared archived states' z signs agree; the
    per-wash clause booleans co-reported. w3 co-reported everywhere
    (e234 finished it).
  * FATES provenance: e234's committed journal traj (w1 28/26, w2
    26/28, w3 29/25 killed/living; Gmail 0/3 washes killed, iPhone
    3/3 — the e226 anchor fates reproduced).

GATES: G_ENV (CPU-only, threads 8 torch / 4 BLAS, psutil load checks
per phase; no GPU — e237 owns that lane), G_SIZE (inherited 124M-with-
reason via e182c), G_CORPUS, G_BATT, G_SUPPORT (FD + the e226 w1:s0
alignment certification, dp <= 0.005), G_CE (bit-exact vs e234's
journaled CE/gnorms), G_DRAWS, G_REPLAY, G_MOMENT, G_STEP, G_E233.

PROVENANCE (extend-don't-repeat): builds on scratch/e240_design.md
(the frozen design), FQ8 (the ideator's Rank 3, scratch/review_
ideator_2026-10-04.md), T215/e233 (the near-miss that named the wind's
memory), T217/e234 (the certified gradient cache + the span's
cross-wash identity context), T198/e226 (the 54-probe support bank,
the cache conventions, the anchor seat, the band-sigma z), e214 (the
belief trajectories / re-probe convention), T139/opt1 (the pace
clause), e179 (the 18-step stickiness), T116/e175 (the no-archive law
read at the WEIGHTS level), e182c/e182c2/e217 (the three-wash archive
+ certified draw streams). NEW: the first reconstruction of the
optimizer's moment substrate over the certified washes; the
killed-vs-living contrast in the applied direction d_t with the
cross-probe null; the supply-echo reference; the v-mask and pace
co-reads; the three-leg applied-step validation (incl. e233's
committed ledger).

Envelope: CPU-only, torch threads 8, progressive PARTIAL metrics +
journal after every wash, load checks per phase, scratch memmap
deleted on DONE / kept on failure. No NOTES/THINKING/QUEUE/STATE
edits (dispatch). Smoke via E240_SMOKE=1 (12 steps, w1 only, 11
probes; nothing adjudicated or gated).

Run:  cd lab && python e240_moment_archive.py     (E240_SMOKE=1 for the
      shakedown; nothing adjudicated or gated in smoke)
"""
from __future__ import annotations

import copy
import json
import math
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

os.environ.setdefault("HF_HUB_OFFLINE", "1")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("OMP_NUM_THREADS", "4")     # numpy/BLAS (small algebra)
os.environ.setdefault("MKL_NUM_THREADS", "4")

import numpy as np                                   # noqa: E402
import torch                                         # noqa: E402

import common                                        # noqa: E402
from common import now_iso, run_dir, save_json       # noqa: E402

import e182c_forgetting_control as e1                # noqa: E402 — the replay machinery, VERBATIM
import e182c2_template as e2                         # noqa: E402 — the template battery, VERBATIM
import e226_interior as e226                         # noqa: E402 — the support bank + wash-grad conventions

THREADS = 8                    # e182c's replay convention (w1 = a threads-8 CPU product)
torch.set_num_threads(THREADS)  # AFTER the imports (e182c sets 8; e226 resets 4)

import torch.nn.functional as F                      # noqa: E402
from scipy.stats import spearmanr                    # noqa: E402

import matplotlib                                    # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt                      # noqa: E402
import textwrap                                      # noqa: E402

try:
    import psutil                                   # noqa: E402
except ImportError:
    psutil = None

SMOKE = os.environ.get("E240_SMOKE") == "1"
CPU = torch.device("cpu")
NAME = "e240_smoke" if SMOKE else "e240"

T0 = time.time()
_log_t0 = time.time()
def log(m: str) -> None:
    print(f"[{time.time() - _log_t0:8.1f}s] {m}", flush=True)

# ------------------------------------------------------------ the frozen cell
WASHES = ("w1",) if SMOKE else ("w1", "w2", "w3")
W_SEED = dict(e226.W_SEED)                     # {w1: 18202, w2: 20261002, w3: 21703}
W_ARCH = e226.W_ARCH                           # archived state checkpoints
W_LATEST = e226.W_LATEST                       # archived step-80 gen states
STEPS = 12 if SMOKE else 80
LATE_WINDOW = list(range(STEPS - 3, STEPS + 1)) if SMOKE \
    else list(range(61, 81))                   # H-FOSSIL's "last 20 steps"
MID_WINDOW = list(range(max(4, STEPS - 8), STEPS + 1)) if SMOKE \
    else list(range(40, 81))                   # H-TRANSIENT's "by +40"
EARLY_WINDOW = list(range(1, (5 if SMOKE else 40)))
PERM_STATES = (2, 10, 40, 80) if not SMOKE else (2, 10)
CACHE_SCALE = e226.CACHE_SCALE                 # 2**14 (e226's fp16 cache convention)
CHUNK = 4_194_304                              # 2**22 coords per chunk (e226's CHUNK)
K_HOT = 2000                                   # e226's primary hot-set k
K_LADDER = (2000, 20000, 200000)
RAM_FLOOR_GB = 16.0                            # e226's floor for the fp16 cache
ANCHOR_G, ANCHOR_I = e226.ANCHOR_G, e226.ANCHOR_I
CK = common.REPO / "runs" / "checkpoints"
SCRATCH = common.REPO / "scratch" / "e240_cache"

# the wash's optimizer hyperparameters — from the e182c wash config, VERBATIM
# (torch.optim.AdamW(net.parameters(), lr=e1.LR, betas=(0.9, 0.95),
#  weight_decay=0.1); torch.nn.utils.clip_grad_norm_(net.parameters(), 1.0))
LR, B1, B2, WD, EPS_ADAM, CLIP = e1.LR, 0.9, 0.95, 0.1, 1e-8, 1.0

# committed records (load-only)
E182C_M = common.REPO / "runs" / "e182c" / "metrics.json"
E182C2_M = common.REPO / "runs" / "e182c2" / "metrics.json"
E182C2_J = common.REPO / "runs" / "e182c2" / "journal_p2.json"
E217_M = common.REPO / "runs" / "e217" / "metrics.json"
E214_M = common.REPO / "runs" / "e214" / "metrics.json"
E216_M = common.REPO / "runs" / "e216" / "metrics.json"
E226_M = common.REPO / "runs" / "e226" / "metrics.json"
E233_M = common.REPO / "runs" / "e233" / "metrics.json"
E234_J = common.REPO / "runs" / "e234" / "journal.json"

REGISTERED = {
    "bars_verbatim": {
        "H-FOSSIL": "the killed probes' supports are overrepresented in "
        "the applied direction at +80 (contrast z >= 2, sustained over "
        "the last 20 steps) — the moments remember what the weights "
        "forgot; the no-archive law's amendment candidate; the "
        "intervention leg unlocks",
        "H-TRANSIENT": "the contrast decays on a ~10-20-step scale "
        "regardless of fate (z < 1 by +40) — the memory is the supply's "
        "echo; e237's pre-Adam cut is exactly right",
        "NEITHER": "no contrast at any state — the moment substrate is "
        "fate-blind",
    },
    "predictions_verbatim": {
        "(a) e179 timescale": "under H-TRANSIENT the decay timescale "
        "matches e179's ~18-step stickiness",
        "(b) FQ3 pace co-read": "FQ3 co-read — v_t's implied "
        "per-coordinate step scale on the fact battery's coordinates vs "
        "T139's pace clause",
        "(c) w2 sign replication": "the w2 reconstruction reproduces the "
        "w1 story in sign",
    },
    "note": "the intervention leg (one moment-only step from +80) is NOT "
        "in this cell; it unlocks only on H-FOSSIL and dispatches "
        "separately",
    "registration": "bars + predictions frozen VERBATIM from "
        "scratch/e240_design.md + the dispatch brief (both frozen BEFORE "
        "this script or any compute); adjudicate against exactly this; "
        "no bar shopping",
}

deviations: list[str] = [
    "The e234 gradient cache's memmaps were deleted on that cell's DONE "
    "(its disclosed lifecycle: 'memmaps deleted only on DONE') — the "
    "certified gradients are REGENERATED here by the identical "
    "deterministic replay and STREAMED into the fp64 moment recursions "
    "(never stored whole). Certified by G_CE (bit-exact CE + gnorm vs "
    "e234's journal), G_DRAWS and G_REPLAY — the regeneration is the "
    "cache, re-derived.",
    "PRIMARY moments are over the CLIPPED gradients (what the wash's "
    "AdamW actually drank — clip 1.0 binds every step: gnorms 3.4-25.7, "
    "clip factors 0.23-0.29); the RAW-gradient flavor (the design's "
    "literal 'cached gradients' reading) runs as a second recursion and "
    "co-report — it differs only through the clip factor's step-to-step "
    "variation. The applied-STEP validation (G_STEP/G_MOMENT/G_E233) "
    "adjudicates the stack: the clipped recursion IS the true state.",
    "The supports are t=0-fixed (e226/e239's rotation disclosure: "
    "supports rotate ~18-20 deg through the wash — the fate-blind tide); "
    "the fp16 cache floor ~5e-4 per cos (e226's measured instrument "
    "floor) is reported against the smallest cross-probe sigma.",
    "The fate labels come from e234's committed journal trajectories "
    "(p at 0 and +80; e214-gated in that cell), killed := p(80) < "
    "0.5*p(0) — e232's standing-zombie belief clause, frozen here "
    "BEFORE compute.",
    "The hot set is e226's own 124M ladder (k=2000 primary, 20000/"
    "200000 co-reported); the fact battery's coordinate set = the union "
    "of the 20 fact probes' top-2000 |s| (ladder co-report).",
    "w3 is co-reported everywhere (the design's 'wash-3 when e234 "
    "finishes it' — it finished); prediction (c)'s bar speaks on w2.",
    "scratch/e240_cache/ holds the fp16 supports memmap (13.4 GB; "
    "scratch is workspace, NOT runs/ or data/); deleted on DONE, kept "
    "on any failure for post-mortem.",
    "No NOTES/THINKING/QUEUE/STATE edits (dispatch).",
    "Smoke mode (E240_SMOKE=1): 12 steps, w1 only, 11 probes; nothing "
    "adjudicated or gated (SMOKE stamp).",
]


# ------------------------------------------------------------ envelope

def cpu_load_check(tag: str) -> dict:
    if psutil is None:
        return {"tag": tag, "psutil": "absent"}
    rec = {"tag": tag,
           "cpu_percent": psutil.cpu_percent(interval=0.5),
           "ram_avail_gb": round(psutil.virtual_memory().available / 2**30, 1)}
    log(f"  [load] {tag}: cpu {rec['cpu_percent']}% "
        f"ram_avail {rec['ram_avail_gb']} GB")
    return rec


def save_journal(rd: Path, journal: dict):
    (rd / "journal.json").write_text(
        json.dumps(journal, indent=1, default=float), encoding="utf-8")


def drift_vs_archived(net, path) -> dict:
    """max|dW| and max relative drift of the LIVE net vs an archived
    checkpoint, compared AT the checkpoint's own step."""
    sdc = torch.load(path, map_location=CPU, weights_only=False)["model"]
    md = mr = 0.0
    with torch.no_grad():
        for (_k, v), (_kb, va) in zip(net.state_dict().items(),
                                      sdc.items()):
            d = (v - va).abs()
            md = max(md, float(d.max().item()))
            mr = max(mr, float((d.norm() / va.norm().clamp(min=1e-12)
                                ).item()))
    del sdc
    return {"max_abs_dw": md, "max_rel_dw": mr}


# ------------------------------------------------------------ the contrast

def contrast(align, killed) -> dict:
    """killed-vs-living contrast of the 54 alignments, z against the 54's
    OWN cross-probe spread (e226's band-sigma convention, two-sample form)."""
    a = np.asarray(align, dtype=np.float64)
    k = np.asarray(killed, dtype=bool)
    K, L = a[k], a[~k]
    md = float(K.mean() - L.mean())
    sd = float(a.std(ddof=1))
    se = sd * math.sqrt(1.0 / len(K) + 1.0 / len(L))
    return {"md": md, "se": se,
            "z": md / se if se > 0 else float("nan"),
            "meanK": float(K.mean()), "meanL": float(L.mean()),
            "sd54": sd, "nK": int(len(K)), "nL": int(len(L))}


def pooled_z(per_wash: list[dict]) -> dict:
    """inverse-variance fixed-effects pool of the per-wash contrasts."""
    mds = np.array([c["md"] for c in per_wash])
    ses = np.array([c["se"] for c in per_wash])
    ok = ses > 0
    if not ok.any():
        return {"z": float("nan"), "md": float("nan"), "se": float("nan")}
    w = 1.0 / ses[ok] ** 2
    md = float((w * mds[ok]).sum() / w.sum())
    se = float(math.sqrt(1.0 / w.sum()))
    return {"z": md / se if se > 0 else float("nan"), "md": md, "se": se}


def perm_check(align, killed, n_perm: int = 20000, seed: int = 240) -> dict:
    """the explicit label-permutation null (the g11 guard's formal check):
    re-label the 54's OWN alignments, record the group-mean difference."""
    rng = np.random.default_rng(seed)
    a = np.asarray(align, dtype=np.float64)
    k = np.asarray(killed, dtype=bool)
    nK = int(k.sum())
    obs = float(a[k].mean() - a[~k].mean())
    n = len(a)
    sims = np.empty(n_perm)
    aa = a.copy()
    for i in range(n_perm):
        rng.shuffle(aa)
        sims[i] = aa[:nK].mean() - aa[nK:].mean()
    sd = float(sims.std(ddof=1))
    p = float((np.abs(sims - sims.mean()) >= abs(obs - sims.mean())).mean())
    return {"obs_md": obs, "perm_sd": sd,
            "perm_z": (obs - sims.mean()) / sd if sd > 0 else float("nan"),
            "perm_p_twosided": p}


# ------------------------------------------------------------ main pieces

def build_batteries(net0, tok):
    """e234's P1 battery build, VERBATIM (module-import conventions)."""
    text = (common.REPO / "data" / "input.txt").read_text(encoding="utf-8")
    e182 = json.loads(e1.E182_METRICS.read_text(encoding="utf-8"))
    e_corp = e182["corpus"]
    e_str = e182["gates"]["G_STR"]
    banned = sorted({s.lower() for rel in e1.POOLS for s, _ in e1.POOLS[rel]}
                    | {a.lower() for rel in e1.POOLS
                       for _, a in e1.POOLS[rel]}
                    | set(e1.BANNED_EXTRA))
    assert banned == e_str["banned"]
    cand, _ = e1.build_candidates(tok)
    for r, b in zip(cand, e1.probe_battery(net0, cand)["probes"]):
        r.update({"p": b["p"], "rank": b["rank"], "top1": b["top1"],
                  "top5": b["top5"]})
    e1.select_battery(cand)
    battery = [r for r in cand if r["kept"]]
    answer_ids = {r["fact"]: r["ans_id"] for r in battery}
    train_ids, _bank_xy, filtered, G_STR, _G_TOK, corpus_stats = \
        e1.build_wash_corpus(tok, text, banned, answer_ids)
    G_CORPUS = {"tokens_after": [corpus_stats["tokens_after"],
                                 e_corp["tokens_after"]],
                "train_tokens": [corpus_stats["train_tokens"],
                                 e_corp["train_tokens"]],
                "banned_list_identical": True}
    G_CORPUS["pass"] = bool(
        G_STR["lines_total"] == e_str["lines_total"]
        and G_STR["lines_dropped"] == e_str["lines_dropped"]
        and corpus_stats["chars_after"] == e_corp["chars_after"]
        and corpus_stats["tokens_after"] == e_corp["tokens_after"]
        and corpus_stats["train_tokens"] == e_corp["train_tokens"])
    ccand, _ = e1.build_control_candidates(tok, filtered.lower(), train_ids,
                                           e_str["banned"], e1.CTRL_POOLS,
                                           e1.CTRL_TMPL)
    for r, b in zip(ccand, e1.probe_battery(net0, ccand)["probes"]):
        r.update({"p": b["p"], "rank": b["rank"], "top1": b["top1"],
                  "top5": b["top5"]})
    e1.select_battery(ccand)
    cbattery = [r for r in ccand if r["kept"]]
    ncand, _ = e1.build_control_candidates(
        tok, filtered.lower(), train_ids, e_str["banned"],
        {"near": e1.NEAR_POOL}, {"near": e1.NEAR_TMPL})
    for r, b in zip(ncand, e1.probe_battery(net0, ncand)["probes"]):
        r.update({"p": b["p"], "rank": b["rank"], "top1": b["top1"],
                  "top5": b["top5"]})
    e1.select_battery(ncand)
    nbattery = [r for r in ncand if r["kept"]]
    tcand, _ = e2.build_tmpl_candidates(tok, filtered.lower(), train_ids,
                                        e_str["banned"])
    for r, b in zip(tcand, e1.probe_battery(net0, tcand)["probes"]):
        r.update({"p": b["p"], "rank": b["rank"], "top1": b["top1"],
                  "top5": b["top5"]})
    e1.select_battery(tcand)
    tbattery = [r for r in tcand if r["kept"]]
    return ({"fact": battery, "ctrl": cbattery, "near": nbattery,
             "tmpl": tbattery}, train_ids, G_CORPUS)


def build_supports(net0, probes54, n_p, N, journal):
    """The 54 t=0 supports as an fp16 memmap (e226's convention) + the FD
    gate + the e226-alignment certification + hot sets + the mutual
    Gram."""
    SCRATCH.mkdir(parents=True, exist_ok=True)
    mm_path = SCRATCH / "supports.npy"
    mm = np.lib.format.open_memmap(mm_path, mode="w+", dtype=np.float16,
                                   shape=(n_p, N))
    fd_records = []
    netFD = copy.deepcopy(net0)
    base_sds = [p.detach().clone() for p in netFD.parameters()]
    for i, pr in enumerate(probes54):
        s_i, p0 = e226.probe_support(net0, pr)
        mm[i] = (s_i * CACHE_SCALE).to(torch.float16).numpy()
        fd = {}
        for eps in (0.02, 0.05):
            e226.add_flat(netFD, base_sds, s_i, eps)
            fd[str(eps)] = e226.probe_p(netFD, pr) - p0
            e226.restore_flat(netFD, base_sds)
        fd_records.append({"fact": pr["fact"], "p0": p0, "fd_dp": fd,
                           "fd_pass": bool(fd["0.02"] > 0)})
        if (i + 1) % 10 == 0:
            log(f"  supports {i + 1}/{n_p}")
    del netFD, base_sds
    mm.flush()
    journal["supports_fd"] = fd_records

    cache_t = torch.from_numpy(np.asarray(mm))       # view (no copy)
    row_norms_t = e226.cache_row_norms(cache_t)
    row_norms = row_norms_t.tolist()
    s_rep, _ = e226.probe_support(net0, probes54[0])
    d_rep = e226.dot_vec_rows(s_rep, cache_t, [0])[0] / row_norms[0]
    del s_rep

    # the hot sets (e226's ladder) + the fact battery's union
    hot_idx = {}
    for i in range(n_p):
        row = torch.from_numpy(np.ascontiguousarray(mm[i])).to(torch.float32)
        for k in K_LADDER:
            hot_idx[(i, k)] = np.sort(np.asarray(
                torch.topk(row.abs(), k).indices, dtype=np.int64))
        del row
    fact_rows = [i for i, pr in enumerate(probes54) if pr["battery"] == "fact"]
    fact_union = np.unique(np.concatenate(
        [hot_idx[(i, K_HOT)] for i in fact_rows]))
    fact_mask = torch.zeros(N, dtype=torch.bool)
    fact_mask[torch.from_numpy(fact_union)] = True

    # the 54x54 mutual-overlap Gram (the g11 disclosure object)
    SS = np.zeros((n_p, n_p), dtype=np.float64)
    for a in range(0, N, CHUNK):
        b = min(a + CHUNK, N)
        Sb = torch.from_numpy(np.ascontiguousarray(mm[:, a:b])).to(torch.float64)
        SS += (Sb @ Sb.T).numpy()
        del Sb
    rn = np.asarray(row_norms)
    cos_mat = SS / np.outer(rn, rn)
    return {"mm_path": mm_path, "mm": mm, "row_norms": row_norms,
            "self_cos_probe0": d_rep, "hot_idx": hot_idx,
            "fact_union": fact_union, "fact_mask": fact_mask,
            "fd_records": fd_records, "cos_mat": cos_mat}


def certify_supports(net0, train_ids, probes54, sup, e226m) -> dict:
    """G_SUPPORT: the w1 draw-1 wash gradient at the pristine weights vs
    e226's committed alignment record (e234's certification block)."""
    e226_align0 = e226m["curves"]["alignment"]["w1"]["0"]
    gen1 = torch.Generator().manual_seed(W_SEED["w1"])
    hi1 = train_ids.shape[0] - e1.SEQ - 1
    off1 = torch.randint(hi1, (e1.BATCH,), generator=gen1)
    x1, y1 = e226.wash_batch(train_ids, off1)
    g1_hat, _ce1, _n1 = e226.wash_grad(net0, x1, y1)
    cache_t = torch.from_numpy(np.asarray(sup["mm"]))
    dots1 = e226.dot_vec_rows(g1_hat, cache_t, list(range(len(probes54))))
    cos1 = {probes54[i]["fact"]: dots1[i] / sup["row_norms"][i]
            for i in range(len(probes54))}
    dp_226 = max(abs(cos1[f] - e226_align0[f]) for f in cos1)
    del g1_hat, dots1, cos1, cache_t
    G = {"fd_pass_n": sum(1 for r in sup["fd_records"] if r["fd_pass"]),
         "n": len(probes54), "determinism_selfcos_probe0": sup["self_cos_probe0"],
         "max_dp_vs_e226_committed_w1s0_alignment": dp_226,
         "tol_dp_226": 0.005}
    G["pass"] = bool(G["fd_pass_n"] == len(probes54)
                     and sup["self_cos_probe0"] > 0.999
                     and dp_226 <= 0.005) if not SMOKE else True
    return G


def replay_wash(net0, train_ids, probes54, sup, journal, load_checks,
                wi: int, w: str, e234_wj) -> dict:
    """One wash: the VERBATIM e182c replay on CPU with the fp64 AdamW
    moment recursions STREAMED over each step's (clipped + raw) gradient;
    per-step reads vs the supports; certifications."""
    S = STEPS
    N = sum(p.numel() for p in net0.parameters())
    n_p = len(probes54)
    sup_mm = sup["mm"]
    row_norms_t = torch.tensor(sup["row_norms"], dtype=torch.float64)
    fact_mask = sup["fact_mask"]
    wj = journal.setdefault(w, {"steps": {}})

    net = copy.deepcopy(net0)
    net.train()
    opt = torch.optim.AdamW(net.parameters(), lr=LR, betas=(B1, B2),
                            weight_decay=WD)
    gen = torch.Generator().manual_seed(W_SEED[w])
    hi = train_ids.shape[0] - e1.SEQ - 1

    m_ = torch.zeros(N, dtype=torch.float64)       # PRIMARY (clipped grads)
    v_ = torch.zeros(N, dtype=torch.float64)
    m2_ = torch.zeros(N, dtype=torch.float64)      # RAW-grad flavor
    v2_ = torch.zeros(N, dtype=torch.float64)
    t_start = time.time()
    arch_states = sorted(W_ARCH[w]) if not SMOKE else []

    for step in range(1, S + 1):
        off = torch.randint(hi, (e1.BATCH,), generator=gen)
        x = torch.stack([train_ids[o: o + e1.SEQ] for o in off])
        y = torch.stack([train_ids[o + 1: o + 1 + e1.SEQ] for o in off])
        logits = net(input_ids=x).logits
        loss = F.cross_entropy(logits.reshape(-1, logits.shape[-1]),
                               y.reshape(-1))
        ce = float(loss.item())
        opt.zero_grad(set_to_none=True)
        loss.backward()
        g_raw = e226.flat_grad(net)                     # fp32 flat
        nrm = float(g_raw.norm(dtype=torch.float64).item())
        if not (nrm > 0 and math.isfinite(nrm)):
            raise RuntimeError(f"{w} s{step}: degenerate gradient")
        tn = torch.nn.utils.clip_grad_norm_(net.parameters(), CLIP)
        tnf = float(tn)
        clip_fac = min(1.0, 1.0 / (tnf + 1e-6))         # torch's formula

        pb = [p.detach().clone() for p in net.parameters()]
        theta_b = torch.cat([t.reshape(-1) for t in pb])

        b1c = 1.0 - B1 ** step
        b2c = 1.0 - B2 ** step
        dots = torch.zeros((n_p, 3), dtype=torch.float64)  # [d, d_raw, g_clip]
        d2 = d2r = g2 = arec = 0.0
        absd_sum = 0.0
        absd_fact = 0.0
        for a in range(0, N, CHUNK):
            b = min(a + CHUNK, N)
            raw64 = g_raw[a:b].to(torch.float64)
            gc64 = raw64 * clip_fac
            m_[a:b].mul_(B1).add_(gc64, alpha=1.0 - B1)
            v_[a:b].mul_(B2).addcmul_(gc64, gc64, value=1.0 - B2)
            m2_[a:b].mul_(B1).add_(raw64, alpha=1.0 - B1)
            v2_[a:b].mul_(B2).addcmul_(raw64, raw64, value=1.0 - B2)
            d = (m_[a:b] / b1c) / ((v_[a:b] / b2c).sqrt() + EPS_ADAM)
            dr = (m2_[a:b] / b1c) / ((v2_[a:b] / b2c).sqrt() + EPS_ADAM)
            Sb = torch.from_numpy(
                np.ascontiguousarray(sup_mm[:, a:b])).to(torch.float64)
            DG = torch.empty((b - a, 3), dtype=torch.float64)
            DG[:, 0] = d
            DG[:, 1] = dr
            DG[:, 2] = gc64
            dots += Sb @ DG
            d2 += float(d.dot(d))
            d2r += float(dr.dot(dr))
            g2 += float(gc64.dot(gc64))
            absd = d.abs()
            absd_sum += float(absd.sum())
            absd_fact += float(absd[fact_mask[a:b]].sum())
            arec += float((WD * theta_b[a:b].to(torch.float64) + d
                           ).pow(2).sum())
            del Sb, DG, d, dr, gc64, raw64, absd
        opt.step()
        live2 = 0.0
        with torch.no_grad():
            for p, pbb in zip(net.parameters(), pb):
                live2 += float((p - pbb).pow(2).sum(dtype=torch.float64))
        del pb, theta_b, g_raw

        applied_rec = LR * math.sqrt(max(arec, 0.0))
        applied_live = math.sqrt(max(live2, 0.0))
        dnorm = math.sqrt(max(d2, 0.0))
        drnorm = math.sqrt(max(d2r, 0.0))
        gcnorm = math.sqrt(max(g2, 0.0))
        dots_np = dots.numpy()
        cos_d = (dots_np[:, 0] / (dnorm * np.asarray(sup["row_norms"])))
        cos_dr = (dots_np[:, 1] / (drnorm * np.asarray(sup["row_norms"])))
        cos_g = (dots_np[:, 2] / (gcnorm * np.asarray(sup["row_norms"])))

        wj["steps"][str(step)] = {
            "ce": ce, "gnorm_raw": nrm, "tn_torch": tnf,
            "clip_fac": clip_fac, "applied_norm_rec": applied_rec,
            "applied_norm_live": applied_live, "dnorm": dnorm,
            "drnorm": drnorm, "gcnorm_post": gcnorm,
            "absd_mean": absd_sum / N,
            "cos_d": cos_d.tolist(), "cos_dr": cos_dr.tolist(),
            "cos_g": cos_g.tolist(),
        }

        # ---- G_REPLAY: drift vs the archived checkpoint at its own step
        if not SMOKE and step in W_ARCH[w]:
            wj.setdefault("replay_cert", {})[str(step)] = \
                drift_vs_archived(net, W_ARCH[w][step])

        # ---- archived-state reads: G_MOMENT, v-mask, pace table
        if not SMOKE and step in arch_states:
            ma = torch.cat([opt.state[p]["exp_avg"].reshape(-1)
                            for p in net.parameters()])
            va = torch.cat([opt.state[p]["exp_avg_sq"].reshape(-1)
                            for p in net.parameters()])
            rel_m = float((m_ - ma.to(torch.float64)).abs().max()
                          / ma.abs().max().clamp(min=1e-30))
            rel_v = float((v_ - va.to(torch.float64)).abs().max()
                          / va.abs().max().clamp(min=1e-30))
            del ma, va
            vsum = float(v_.sum())
            vhot = {}
            for i in range(n_p):
                vhot[probes54[i]["fact"]] = {
                    str(k): float(v_[torch.from_numpy(
                        sup["hot_idx"][(i, k)])].sum() / vsum)
                    for k in K_LADDER}
            n_act = int((v_ > 0).sum())
            wj.setdefault("arch_reads", {})[str(step)] = {
                "moment_cert": {"rel_m_max": rel_m, "rel_v_max": rel_v},
                "vhot_share": vhot,
                "pace": {"absd_mean_global": absd_sum / N,
                         "absd_mean_fact": absd_fact / len(sup["fact_union"]),
                         "n_fact_coords": int(len(sup["fact_union"])),
                         "n_active_coords": n_act,
                         "dnorm": dnorm, "lr_times_dnorm": LR * dnorm,
                         "applied_norm_live": applied_live,
                         "dnorm_over_sqrt_nact":
                             dnorm / math.sqrt(max(n_act, 1))},
            }

        if step % 10 == 0 or step == S:
            log(f"  [{w} replay] s{step:3d}/{S} CE {ce:.4f} |g| {nrm:.2f} "
                f"clip {clip_fac:.4f} applied {applied_live:.4f} "
                f"({time.time() - t_start:.0f}s)")
            journal[w] = wj
            save_journal(RD, journal)

    # ---- G_DRAWS: bit-exact generator state vs the archived *_latest
    gen_ok = None
    if not SMOKE:
        archived = torch.load(W_LATEST[w], map_location=CPU,
                              weights_only=False)["gen"]
        gen_ok = bool(torch.equal(gen.get_state(), archived))

    # ---- G_CE: bit-exact vs e234's journaled CE + gnorms
    ce_cert = gnorm_cert = None
    if e234_wj is not None:
        dce = max(abs(wj["steps"][str(t)]["ce"] - e234_wj["ces"][t - 1])
                  for t in range(1, S + 1))
        dgn = max(abs(wj["steps"][str(t)]["gnorm_raw"]
                      - e234_wj["gnorms"][t - 1]) for t in range(1, S + 1))
        ce_cert, gnorm_cert = dce, dgn

    out = {"gen_ok": gen_ok, "ce_cert": ce_cert, "gnorm_cert": gnorm_cert,
           "replay_cert": wj.get("replay_cert", {}),
           "arch_reads": wj.get("arch_reads", {})}
    journal[w] = wj
    save_journal(RD, journal)
    log(f"{w}: replay done ({time.time() - t_start:.0f}s); gen_ok {gen_ok}; "
        f"dCE {ce_cert}; dgnorm {gnorm_cert}")
    del net, opt, m_, v_, m2_, v2_
    return out


# ------------------------------------------------------------ plots

def plot_decay(rd, tsteps, z_pool, z_pool_raw, z_pool_g, per_wash_z,
               verdict_line):
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    ax = axes[0]
    ax.axhline(2.0, color="#c0392b", ls="--", lw=1, alpha=0.8)
    ax.axhline(1.0, color="#e67e22", ls=":", lw=1, alpha=0.8)
    ax.axhline(0.0, color="0.6", lw=0.8)
    ax.axhline(-1.0, color="#e67e22", ls=":", lw=1, alpha=0.8)
    ax.axhline(-2.0, color="#c0392b", ls="--", lw=1, alpha=0.8)
    if not SMOKE:
        ax.axvspan(61, 80, color="#fdebd0", alpha=0.7, zorder=0)
        ax.axvline(18, color="#1a6faf", ls="-.", lw=1.2, alpha=0.9)
        ax.text(18.6, 2.15, "e179's 18", fontsize=8, color="#1a6faf")
    ax.plot(tsteps, z_pool, "o-", color="#8e44ad", ms=3, lw=1.6,
            label="z(d_t) — the applied direction (PRIMARY)")
    ax.plot(tsteps, z_pool_raw, "-", color="#16a085", lw=1.1, alpha=0.8,
            label="z(d_t raw-flavor) (co-report)")
    ax.plot(tsteps, z_pool_g, "-", color="#5d6d7e", lw=1.3, alpha=0.9,
            label="z(g_t) — the SUPPLY reference (echo)")
    ax.set_xlabel("wash step t")
    ax.set_ylabel("killed-vs-living contrast z (cross-probe null)")
    ax.set_title("THE CONTRAST DECAY CURVE — pooled (fixed-effects, 3 washes)",
                 fontsize=10)
    ax.legend(fontsize=8, loc="best")
    ax.grid(alpha=0.25)
    ax = axes[1]
    for wtag, c in zip(("w1", "w2", "w3"),
                       ("#8e44ad", "#c0392b", "#1a6faf")):
        if wtag not in per_wash_z:
            continue
        ax.plot(tsteps, per_wash_z[wtag], "o-", ms=3, color=c, alpha=0.8,
                label=f"{wtag}")
    ax.axhline(2.0, color="#c0392b", ls="--", lw=1, alpha=0.8)
    ax.axhline(1.0, color="#e67e22", ls=":", lw=1, alpha=0.8)
    ax.axhline(0.0, color="0.6", lw=0.8)
    if not SMOKE:
        ax.axvspan(61, 80, color="#fdebd0", alpha=0.7, zorder=0)
    ax.set_xlabel("wash step t")
    ax.set_ylabel("z(d_t) per wash")
    ax.set_title("PER-WASH replication read", fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25)
    fig.suptitle("E240 — THE MOMENT ARCHIVE: does d_t = m/sqrt(v) carry the "
                 "eaten facts after the weights forgot them?\n"
                 + textwrap.fill(verdict_line, 120), fontsize=10.5)
    fig.tight_layout(rect=(0, 0, 1, 0.88))
    png = rd / f"{NAME}_decay.png"
    fig.savefig(png, dpi=130)
    plt.close(fig)
    return png


def plot_distributions(rd, probes54, fates, journal, z_at):
    washes = [w for w in WASHES if w in journal and journal[w].get("steps")]
    fig, axes = plt.subplots(1, max(len(washes), 1),
                             figsize=(5.0 * max(len(washes), 1), 5.4),
                             squeeze=False)
    rng = np.random.default_rng(0)
    for ax, w in zip(axes[0], washes):
        cos80 = np.array(journal[w]["steps"][str(STEPS)]["cos_d"])
        k = np.array([fates[w][pr["fact"]] for pr in probes54])
        xs_k = rng.uniform(-0.22, 0.22, size=int(k.sum()))
        xs_l = rng.uniform(-0.22, 0.22, size=int((~k).sum()))
        ax.scatter(xs_k, cos80[k], s=30, alpha=0.8, color="#c0392b",
                   label=f"killed (n={int(k.sum())})")
        ax.scatter(xs_l, cos80[~k], s=30, alpha=0.8, color="#1a6faf",
                   label=f"living (n={int((~k).sum())})")
        ax.hlines(cos80[k].mean(), -0.35, 0.35, color="#c0392b", lw=2)
        ax.hlines(cos80[~k].mean(), -0.35, 0.35, color="#1a6faf", lw=2)
        gi = [i for i, pr in enumerate(probes54) if pr["fact"] == ANCHOR_G]
        ii = [i for i, pr in enumerate(probes54) if pr["fact"] == ANCHOR_I]
        for lbl, idx, mk in (("G", gi, "^"), ("i", ii, "v")):
            if idx:
                ax.scatter([0.3], [cos80[idx[0]]], marker=mk, s=90,
                           color="black", zorder=5)
                ax.annotate(lbl, (0.3, cos80[idx[0]]),
                            textcoords="offset points", xytext=(8, 0),
                            fontsize=10, weight="bold")
        if w in z_at:
            c = z_at[w]
            ax.set_title(f"{w} @ +{STEPS}: z={c['z']:+.2f} "
                         f"(md {c['md']:+.2e}, sd54 {c['sd54']:.1e})",
                         fontsize=9.5)
        ax.set_xlim(-0.45, 0.45)
        ax.set_ylabel(r"$\cos(d_{80},\ s_i)$", fontsize=11)
        ax.legend(fontsize=8, loc="upper right")
        ax.grid(alpha=0.25, axis="y")
    fig.suptitle("E240 — THE +80 DISTRIBUTIONS: the applied direction's "
                 "alignment per probe, killed vs living\n(killed supports "
                 "OVERREPRESENTED in d_t reads as more-POSITIVE alignment; "
                 "G = Gmail the holder, i = iPhone the killed anchor)",
                 fontsize=10)
    fig.tight_layout(rect=(0, 0, 1, 0.88))
    png = rd / f"{NAME}_distributions.png"
    fig.savefig(png, dpi=130)
    plt.close(fig)
    return png


def plot_validation(rd, journal, e233_ledger, ce_dev):
    fig, axes = plt.subplots(1, 4, figsize=(19, 4.8))
    # (a) the design's validation leg: w1 applied-norm trajectory vs e233-C
    ax = axes[0]
    mine = [journal["w1"]["steps"][str(t)]["applied_norm_rec"]
            for t in range(1, STEPS + 1)]
    theirs = [e233_ledger[str(t)]["applied_norm"]
              for t in range(1, STEPS + 1)]
    ax.plot(range(1, STEPS + 1), mine, lw=1.8, color="#8e44ad",
            label="E240 reconstruction (CPU, fp64 recursion)")
    ax.plot(range(1, STEPS + 1), theirs, lw=1.2, ls="--", color="#c0392b",
            label="e233 committed C-arm (GPU fp32)")
    ax.set_xlabel("step"); ax.set_ylabel("||applied step||")
    ax.set_title("THE e233 VALIDATION (w1)", fontsize=10)
    ax.legend(fontsize=7.5); ax.grid(alpha=0.25)
    # (b) reconstructed vs LIVE optimizer step norm (machine precision)
    ax = axes[1]
    rec = np.array(mine)
    live = np.array([journal["w1"]["steps"][str(t)]["applied_norm_live"]
                     for t in range(1, STEPS + 1)])
    ax.scatter(live, rec, s=14, color="#16a085")
    lim = [0, max(rec.max(), live.max()) * 1.06]
    ax.plot(lim, lim, "k--", lw=0.8)
    rel = np.abs(rec - live) / np.maximum(live, 1e-30)
    ax.set_xlabel("live ||Δθ|| (torch's own step)")
    ax.set_ylabel("reconstructed ||Δθ||")
    ax.set_title(f"rec vs LIVE: max rel {rel.max():.2e}", fontsize=10)
    ax.grid(alpha=0.25)
    # (c) m/v vs the live optimizer state at archived states
    ax = axes[2]
    st_labels, rm, rv = [], [], []
    for w in WASHES:
        for st, rcd in (journal.get(w, {}).get("arch_reads", {})
                        or {}).items():
            st_labels.append(f"{w}:{st}")
            rm.append(rcd["moment_cert"]["rel_m_max"])
            rv.append(rcd["moment_cert"]["rel_v_max"])
    xx = np.arange(len(st_labels))
    ax.bar(xx - 0.18, rm, 0.36, color="#8e44ad", label="max rel |m - m_live|")
    ax.bar(xx + 0.18, rv, 0.36, color="#e67e22",
           label="max rel |v - v_live|")
    ax.set_xticks(xx); ax.set_xticklabels(st_labels, fontsize=7,
                                          rotation=45)
    ax.set_yscale("log")
    ax.set_title("moment recursion vs live state (archived states)",
                 fontsize=9.5)
    ax.legend(fontsize=7.5); ax.grid(alpha=0.25, axis="y")
    # (d) CE bit-exactness vs e234's committed journal
    ax = axes[3]
    if ce_dev is not None:
        ax.bar(["w1", "w2", "w3"][:len(ce_dev)], ce_dev,
               color="#1a6faf")
        ax.set_ylabel("max |ΔCE| vs e234 journal")
        ax.set_title("the regeneration certificate (bit-exact replay)",
                     fontsize=10)
        ax.grid(alpha=0.25, axis="y")
    fig.suptitle("E240 — THE APPROXIMATION STACK DISCLOSED AND VALIDATED "
                 "(reconstruction ~ live optimizer at machine precision; "
                 "~ e233's committed product at the CPU/GPU texture tier)",
                 fontsize=10)
    fig.tight_layout(rect=(0, 0, 1, 0.9))
    png = rd / f"{NAME}_validation.png"
    fig.savefig(png, dpi=130)
    plt.close(fig)
    return png


# ------------------------------------------------------------ main

RD = None

def main():
    global RD
    rd = run_dir(NAME)
    RD = rd
    jp = rd / "journal.json"
    log(f"E240 — THE MOMENT ARCHIVE (smoke={SMOKE}) -> {rd}")

    metrics = {
        "experiment": "e240_moment_archive",
        "phase": "the certified wash gradients re-derived by deterministic "
                 "replay and streamed into the fp64 AdamW moment "
                 "recursions; the applied direction d_t = m/sqrt(v) read "
                 "against the 54 t=0 supports, killed vs living; the "
                 "three-leg applied-step validation",
        "date": now_iso(),
        "status": "PARTIAL: startup",
        "registration": REGISTERED["registration"],
        "registered_prediction": REGISTERED,
        "question": ("does Adam's optimizer state retain the eaten facts' "
                     "directions after the weights have forgotten them?"),
        "builds_on": [
            "scratch/e240_design.md (the frozen design)",
            "FQ8 (the ideator's Rank 3, 2026-10-04)",
            "T215 / e233 (the near-miss that named the wind's memory)",
            "T217 / e234 (the certified gradient cache + journal; the "
            "span's cross-wash identity context)",
            "T198 / e226 (the 54-probe support bank, the cache + z "
            "conventions, the anchor seat)",
            "e214 (the belief trajectories; the fate records), T212/e232 "
            "(the standing-zombie belief clause)",
            "T139 / opt1 (the pace clause), e179 (the 18-step stickiness)",
            "T116 / e175 (the no-archive law, read at the WEIGHTS level)",
            "e182c/e182c2/e217 (the three-wash archive + draw streams)",
        ],
        "whats_new": [
            "the first reconstruction of the OPTIMIZER-STATE substrate "
            "over the certified washes (m_t, v_t, d_t = m/sqrt(v) at "
            "every step, fp64, both clip flavors)",
            "the killed-vs-living contrast of the applied direction "
            "against the 54 t=0 supports with the cross-probe null "
            "(z(t) decay curve, permutation-checked)",
            "the supply-echo reference z_g(t) (the interpretation layer: "
            "the fossil read is z_d OVER the echo)",
            "the v-mask read (v's mass on the supports' hot sets) and "
            "the FQ3 pace co-read at the archived states",
            "the three-leg applied-step validation (machine-precision "
            "recursion; e233's committed C-arm ledger)",
        ],
        "smoke": SMOKE,
    }

    def write_metrics(status):
        metrics["status"] = status
        metrics["timing"] = {"total_s": round(time.time() - T0, 1)}
        save_json(rd / "metrics.json", metrics)

    journal: dict = {}
    if jp.exists():
        try:
            journal = json.loads(jp.read_text(encoding="utf-8"))
            log(f"journal restored: {list(journal)}")
        except Exception as e:                              # noqa: BLE001
            log(f"journal unreadable ({e}); starting fresh")
            journal = {}

    load_checks: list[dict] = [cpu_load_check("launch")]
    metrics["load_checks"] = load_checks

    # ------------------------------------------------ P0 the committed records
    for p in (E182C_M, E182C2_M, E182C2_J, E217_M, E214_M, E216_M, E226_M,
              E233_M, E234_J):
        if not p.exists():
            log(f"FATAL: committed record missing: {p}")
            return 1
    e226m = json.loads(E226_M.read_text(encoding="utf-8"))
    e233m = json.loads(E233_M.read_text(encoding="utf-8"))
    e234j = json.loads(E234_J.read_text(encoding="utf-8"))
    e216m = json.loads(E216_M.read_text(encoding="utf-8"))
    p1m = json.loads(E182C_M.read_text(encoding="utf-8"))
    c2m = json.loads(E182C2_M.read_text(encoding="utf-8"))
    j2 = json.loads(E182C2_J.read_text(encoding="utf-8"))
    u3m = json.loads(E217_M.read_text(encoding="utf-8"))
    e233_ledger = e233m["ledgers"]["C"]
    w1_rec = {s["step"]: s for s in p1m["states"]}
    w1_tmpl_rec = {s["step"]: s for s in c2m["part1_template"]["states"]}
    e216_rows = {r["fact"]: r for r in e216m["residual"]["table"]}
    assert len(e216_rows) == 54
    metrics["provenance_records"] = {
        "w1": str(E182C_M), "w1_tmpl": str(E182C2_M), "w2": str(E182C2_J),
        "w3": str(E217_M), "supports+alignments": str(E226_M),
        "applied_steps_validation": str(E233_M),
        "gradient_cache_regeneration": str(E234_J),
        "families": str(E216_M),
    }

    # ------------------------------------------------ P1 organism + batteries
    tok, net0, org_meta = e1.load_organism()
    metrics["organism"] = {**org_meta, "torch_threads": THREADS}
    G_SIZE = {"params": org_meta["params"], "ceiling": e1.SIZE_CEILING,
              "reason": e1.SIZE_REASON,
              "pass": bool(org_meta["params"] <= e1.SIZE_CEILING)}
    assert G_SIZE["pass"]
    metrics["size_gate"] = G_SIZE

    bats, train_ids, G_CORPUS = build_batteries(net0, tok)
    metrics["gates"] = {"G_SIZE": G_SIZE, "G_CORPUS": G_CORPUS}
    log("G_CORPUS: " + ("PASS" if G_CORPUS["pass"] else "FAIL"))
    assert G_CORPUS["pass"] or SMOKE
    write_metrics("PARTIAL: organism + corpus certified")

    def _probes(state_rec, batt):
        return {f: v["p"] for f, v in state_rec[batt]["probes"].items()}
    G_BATT = {}
    for b, bl in bats.items():
        mine_p = {r["fact"]: r["p"] for r in bl}
        ref1 = _probes(w1_rec[0], b) if b != "tmpl" \
            else _probes(w1_tmpl_rec[0], "tmpl")
        G_BATT[b] = {"n": len(bl),
                     "set_equal_committed": bool(set(mine_p) == set(ref1)),
                     "max_dp_w1": max(abs(mine_p[f] - v)
                                      for f, v in ref1.items())}
    G_BATT["pass"] = bool(all(G_BATT[b]["set_equal_committed"]
                              and G_BATT[b]["max_dp_w1"] <= 0.010
                              for b in bats)) or SMOKE
    metrics["gates"]["G_BATT"] = G_BATT
    log("G_BATT: " + ("PASS" if G_BATT["pass"] else "FAIL") + " | "
        + " | ".join(f"{b} n {G_BATT[b]['n']} dp "
                     f"{G_BATT[b]['max_dp_w1']:.2e}" for b in bats))
    if not G_BATT["pass"]:
        write_metrics("PARTIAL: G_BATT FAILED — halted")
        return 1

    probes54: list[dict] = []
    for b in ("fact", "ctrl", "near", "tmpl"):
        for r in bats[b]:
            probes54.append({**r, "battery": b,
                             "family6": e216_rows[r["fact"]]["family6"]})
    assert len(probes54) == 54
    if SMOKE:
        keep = {ANCHOR_G, ANCHOR_I,
                "The gaming console made by Microsoft->Xbox",
                "The web browser made by Google->Chrome",
                "The tablet made by Apple->iPad",
                "The music store made by Apple->iTunes",
                "The game console made by Sony->PlayStation",
                "The social network founded by Mark Zuckerberg->Facebook",
                "France->Paris", "Massachusetts->Boston",
                "Georgia->Atlanta"}
        probes54 = [r for r in probes54 if r["fact"] in keep]
        log(f"SMOKE: probe subset n={len(probes54)}")
    n_p = len(probes54)
    metrics["probes"] = [{"i": i, "fact": r["fact"], "battery": r["battery"],
                          "family6": r["family6"]} for i, r in
                         enumerate(probes54)]
    N_PARAMS = sum(p.numel() for p in net0.parameters())

    # ------------------------------------------------ P2 the supports bank
    load_checks.append(cpu_load_check("supports build"))
    if psutil is not None and \
            psutil.virtual_memory().available / 2**30 < RAM_FLOOR_GB:
        log("FATAL: RAM below floor for the supports cache")
        write_metrics("PARTIAL: RAM floor hit — HALT")
        return 1
    sup = build_supports(net0, probes54, n_p, N_PARAMS, journal)
    G_SUPPORT = certify_supports(net0, train_ids, probes54, sup, e226m)
    metrics["gates"]["G_SUPPORT"] = G_SUPPORT
    log(f"G_SUPPORT: fd {G_SUPPORT['fd_pass_n']}/{n_p}; probe-0 self-cos "
        f"{G_SUPPORT['determinism_selfcos_probe0']:.6f}; max dp vs e226 "
        f"w1:s0 {G_SUPPORT['max_dp_vs_e226_committed_w1s0_alignment']:.5f} "
        f"-> {'PASS' if G_SUPPORT['pass'] else 'FAIL'}")
    if not G_SUPPORT["pass"]:
        write_metrics("PARTIAL: G_SUPPORT FAILED — halted before replays")
        return 1
    save_journal(rd, journal)
    write_metrics("PARTIAL: supports bank rebuilt + certified vs e226")

    # the mutual-overlap disclosure (g11 guard)
    cos_mat = sup.pop("cos_mat")

    # ------------------------------------------------ P3 the fates
    fates = {}
    fate_stats = {}
    fate_end_state = 10 if SMOKE else 80     # e234's full journal states
    for w in WASHES:
        p0 = {r["fact"]: r["p"] for r in e234j[w]["traj"]["0"]}
        p80 = {r["fact"]: r["p"]
               for r in e234j[w]["traj"][str(fate_end_state)]}
        fates[w] = {pr["fact"]: bool(p80[pr["fact"]] < 0.5 * p0[pr["fact"]])
                    for pr in probes54}
        nk = sum(fates[w].values())
        fate_stats[w] = {"n_killed": nk, "n_living": n_p - nk}
    metrics["fates"] = {
        "definition": "killed := p(+80) < 0.5*p(0) (e232's standing-zombie "
                      "belief clause) on e234's committed journal "
                      "trajectories (e214-gated in that cell)",
        "per_wash": fate_stats,
        "anchor_check": {"Gmail": [fates[w][ANCHOR_G] for w in WASHES],
                         "iPhone": [fates[w][ANCHOR_I] for w in WASHES]},
    }
    log("fates: " + " | ".join(f"{w} killed {fate_stats[w]['n_killed']}"
                               for w in WASHES))

    killed_counts = {pr["fact"]: sum(fates[w][pr["fact"]] for w in WASHES)
                     for pr in probes54}
    majority_killed = {pr["fact"]: killed_counts[pr["fact"]] >= 2
                       for pr in probes54}

    # ------------------------------------------------ P4 the replays
    replay_out = {}
    for wi, w in enumerate(WASHES):
        load_checks.append(cpu_load_check(f"replay {w}"))
        if journal.get(w, {}).get("steps") and \
                len(journal[w]["steps"]) == STEPS and \
                "cos_d" in journal[w]["steps"][str(STEPS)]:
            log(f"{w}: already complete in journal — skipping replay")
            replay_out[w] = {"gen_ok": None, "ce_cert": None,
                             "gnorm_cert": None,
                             "arch_reads": journal[w].get("arch_reads", {}),
                             "replay_cert": journal[w].get("replay_cert", {})}
            continue
        e234_wj = e234j.get(w) if not SMOKE else None
        replay_out[w] = replay_wash(net0, train_ids, probes54, sup,
                                    journal, load_checks, wi, w, e234_wj)
        write_metrics(f"PARTIAL: replay {w} done "
                      f"(gen_ok {replay_out[w]['gen_ok']})")

    G_DRAWS = {"per_wash": {w: replay_out[w]["gen_ok"] for w in WASHES},
               "pass": bool(all(replay_out[w]["gen_ok"] is not False
                                for w in WASHES)) or SMOKE}
    ce_dev = [replay_out[w]["ce_cert"] for w in WASHES]
    gn_dev = [replay_out[w]["gnorm_cert"] for w in WASHES]
    G_CE = {"max_abs_dce_per_wash": ce_dev,
            "max_abs_dgnorm_per_wash": gn_dev,
            "tol": 1e-6,
            "note": "bit-exactness of the regeneration vs e234's "
                    "journaled replay (the cache, re-derived)",
            "pass": bool(all(d is not None and d <= 1e-6 for d in ce_dev)
                         and all(d is not None and d <= 1e-6
                                 for d in gn_dev)) or SMOKE}
    G_REPLAY = {"per_wash": {w: replay_out[w]["replay_cert"]
                             for w in WASHES},
                "note": "drift vs the archived checkpoints at their own "
                        "step (w1 CPU-origin ~0 expected; w2/w3 "
                        "GPU-fp32-origin TEXTURE tier ~1.5e-3, disclosed)",
                "tol_abs": {"w1": 1e-3, "w2": 1e-2, "w3": 1e-2}}
    _gr_ok = True
    for w in WASHES:
        for st, rec in (replay_out[w]["replay_cert"] or {}).items():
            if isinstance(rec, dict) and "max_abs_dw" in rec:
                if rec["max_abs_dw"] > G_REPLAY["tol_abs"][w]:
                    _gr_ok = False
    G_REPLAY["pass"] = bool(_gr_ok) or SMOKE
    metrics["gates"].update({"G_DRAWS": G_DRAWS, "G_CE": G_CE,
                             "G_REPLAY": G_REPLAY})
    log(f"G_DRAWS: {G_DRAWS['per_wash']} | G_CE: dCE {ce_dev}")

    # ------------------------------------------------ P5 the reads
    tsteps = list(range(1, STEPS + 1))
    z_curves = {w: {"d": [], "dr": [], "g": []} for w in WASHES}
    sd54_min = float("inf")
    for w in WASHES:
        kw = [fates[w][pr["fact"]] for pr in probes54]
        for t in tsteps:
            row = journal[w]["steps"][str(t)]
            for tag, key in (("d", "cos_d"), ("dr", "cos_dr"),
                             ("g", "cos_g")):
                c = contrast(row[key], kw)
                z_curves[w][tag].append(c["z"])
                sd54_min = min(sd54_min, c["sd54"])
    z_pool = {"d": [], "dr": [], "g": []}
    md_pool = {"d": [], "g": []}
    for ti, t in enumerate(tsteps):
        for tag in ("d", "dr", "g"):
            per = [contrast(journal[w]["steps"][str(t)][
                {"d": "cos_d", "dr": "cos_dr", "g": "cos_g"}[tag]],
                [fates[w][pr["fact"]] for pr in probes54]) for w in WASHES]
            z_pool[tag].append(pooled_z(per)["z"])
            if tag in ("d", "g"):
                md_pool[tag].append(pooled_z(per)["md"])
    z_at80 = {w: contrast(journal[w]["steps"][str(STEPS)]["cos_d"],
                          [fates[w][pr["fact"]] for pr in probes54])
              for w in WASHES}

    # the permutation null checks (the g11 guard's formal co-report)
    perm_checks = []
    for w in WASHES:
        kw = [fates[w][pr["fact"]] for pr in probes54]
        for st in PERM_STATES:
            if str(st) in journal[w]["steps"]:
                perm_checks.append(
                    {"wash": w, "step": st,
                     **perm_check(journal[w]["steps"][str(st)]["cos_d"], kw)})

    # the mean-of-per-wash-z co-report (does not inflate under probe
    # dependence across washes — the fixed-effects pool treats the three
    # washes as independent, which the shared probes violate; disclosed)
    z_meanof = {"d": [], "g": []}
    for tag in ("d", "g"):
        for ti in range(len(tsteps)):
            z_meanof[tag].append(float(np.mean(
                [z_curves[w][tag][ti] for w in WASHES])))

    # the majority-fate co-report on PER-PROBE MEAN alignments (54 values,
    # one per probe — the probe-level-dependent form of the pooled read)
    maj = {"d": [], "g": []}
    for t in tsteps:
        for tag in ("d", "g"):
            key = {"d": "cos_d", "g": "cos_g"}[tag]
            vals = [float(np.mean([journal[w]["steps"][str(t)][key][i]
                                   for w in WASHES]))
                    for i in range(n_p)]
            maj[tag].append(contrast(vals, list(majority_killed.values()))
                            ["z"])

    # the mutual-overlap disclosure (g11)
    killed_mask_w = {w: np.array([fates[w][pr["fact"]]
                                  for pr in probes54]) for w in WASHES}
    off_diag = cos_mat[~np.eye(n_p, dtype=bool)]
    overlap_disc = {
        "mean_pairwise_cos_all_probes": float(off_diag.mean()),
        "max_pairwise_cos": float(off_diag.max()),
        "note": "the probes' own mutual overlaps (the null's substrate); "
                "a shared-hot-set artifact would inflate within-group "
                "co-movement — the permutation checks + sd54 null guard "
                "against it",
    }
    for w in WASHES:
        k = killed_mask_w[w]
        overlap_disc[f"{w}_within_killed_mean_cos"] = float(
            cos_mat[np.ix_(k, k)][~np.eye(int(k.sum()), dtype=bool)].mean()
            if k.sum() > 1 else float("nan"))
        overlap_disc[f"{w}_within_living_mean_cos"] = float(
            cos_mat[np.ix_(~k, ~k)][~np.eye(int((~k).sum()),
                                           dtype=bool)].mean()
            if (~k).sum() > 1 else float("nan"))
        overlap_disc[f"{w}_cross_mean_cos"] = float(
            cos_mat[np.ix_(k, ~k)].mean())

    # --------------------------------------------- P6 the adjudication
    late_z = [z_pool["d"][t - 1] for t in LATE_WINDOW]
    mid_z = [z_pool["d"][t - 1] for t in MID_WINDOW]
    early_z = [z_pool["d"][t - 1] for t in EARLY_WINDOW]
    n_late_ge2 = sum(1 for z in late_z if z >= 2.0)
    b_fossil = bool(min(late_z) >= 2.0)
    b_transient = bool(all(z < 1.0 for z in mid_z)
                       and max(early_z) >= 2.0)
    verdict = ("H-FOSSIL" if b_fossil else
               ("H-TRANSIENT" if b_transient else "NEITHER"))
    contingency = None
    if not b_fossil and not b_transient and max(early_z + mid_z) >= 2.0 \
            and not all(z < 1.0 for z in mid_z):
        contingency = ("an early/late contrast settles in [1,2) over "
                       "40..80 — matches no bar; NEITHER with numbers "
                       "verbatim")

    # the decay statistics (prediction (a))
    t_peak = int(tsteps[int(np.nanargmax(z_pool["d"]))])
    t_cross = None
    for i in range(len(tsteps)):
        if all(z < 1.0 for z in z_pool["d"][i:]):
            t_cross = tsteps[i]
            break
    fit_win = [i for i in range(min(40, STEPS))
               if md_pool["d"][i] > 0]
    tau = half_life = None
    if len(fit_win) >= 5:
        xs = np.array([tsteps[i] for i in fit_win], dtype=np.float64)
        ys = np.log(np.array([md_pool["d"][i] for i in fit_win]))
        slope, intercept = np.polyfit(xs, ys, 1)
        if slope < 0:
            tau = float(-1.0 / slope)
            half_life = float(math.log(2) * tau)

    per_wash_verdicts = {}
    for w in WASHES:
        zl = [z_curves[w]["d"][t - 1] for t in LATE_WINDOW]
        zm = [z_curves[w]["d"][t - 1] for t in MID_WINDOW]
        ze = [z_curves[w]["d"][t - 1] for t in EARLY_WINDOW]
        per_wash_verdicts[w] = {
            "late_min_z": float(min(zl)), "mid_max_z": float(max(zm)),
            "early_max_z": float(max(ze)),
            "b_fossil": bool(min(zl) >= 2.0),
            "b_transient": bool(all(z < 1.0 for z in zm)
                                and max(ze) >= 2.0)}

    # prediction (c): w2 vs w1 in sign
    pred_c = None
    if "w1" in z_curves and "w2" in z_curves and not SMOKE:
        shared_arch = [10, 50, 80]
        agree = [bool(np.sign(z_curves["w1"]["d"][t - 1])
                      == np.sign(z_curves["w2"]["d"][t - 1]))
                 for t in shared_arch]
        r = float(np.corrcoef(z_curves["w1"]["d"], z_curves["w2"]["d"])[0, 1])
        late_sign_agree = bool(np.sign(np.mean(
            [z_curves["w1"]["d"][t - 1] for t in LATE_WINDOW]))
            == np.sign(np.mean([z_curves["w2"]["d"][t - 1]
                                for t in LATE_WINDOW])))
        pred_c = {"sign_agreement_archived_states": agree,
                  "n_agree": int(sum(agree)), "of": len(agree),
                  "z_curve_pearson_r": r,
                  "late_window_sign_agrees": late_sign_agree,
                  "reproduces_in_sign": bool(late_sign_agree
                                             and sum(agree) >= 2)}

    # prediction (b): the pace table
    pace_table = []
    for w in WASHES:
        for st, rcd in sorted((journal.get(w, {}).get("arch_reads", {})
                               or {}).items(), key=lambda kv: int(kv[0])):
            p = rcd["pace"]
            ratio = (p["absd_mean_fact"] / p["absd_mean_global"]
                     if p["absd_mean_global"] > 0 else float("nan"))
            pace_table.append({
                "wash": w, "step": int(st),
                "absd_mean_global": p["absd_mean_global"],
                "absd_mean_fact_coords": p["absd_mean_fact"],
                "ratio_fact_over_global": ratio,
                "n_active_coords": p["n_active_coords"],
                "dnorm_over_sqrt_nact": p["dnorm_over_sqrt_nact"],
                "lr_times_dnorm": p["lr_times_dnorm"],
                "applied_norm_live": p["applied_norm_live"],
                "clock_clause_rel_dev": (abs(p["lr_times_dnorm"]
                                             - p["applied_norm_live"])
                                         / p["applied_norm_live"]),
            })
    pace_co_moves = bool(pace_table and all(
        0.9 <= r["ratio_fact_over_global"] <= 1.1 for r in pace_table))

    # prediction (a) assessment
    pred_a = {"binding": verdict == "H-TRANSIENT",
              "t_cross_z_lt_1": t_cross, "t_peak": t_peak,
              "exp_tau_steps": tau, "exp_half_life_steps": half_life,
              "e179_stickiness_steps": 18,
              "beta2_window_1_over_1m1b2": 1.0 / (1.0 - B2),
              "matches_18_within_50pct": bool(
                  half_life is not None
                  and 9.0 <= half_life <= 27.0)}

    # the e233 validation leg
    e233_vals = {"max_rel_dev": None, "median_rel_dev": None,
                 "spearman": None}
    if not SMOKE and "w1" in journal:
        mine = np.array([journal["w1"]["steps"][str(t)]["applied_norm_rec"]
                         for t in range(1, STEPS + 1)])
        theirs = np.array([e233_ledger[str(t)]["applied_norm"]
                           for t in range(1, STEPS + 1)])
        rel = np.abs(mine - theirs) / theirs
        e233_vals = {"max_rel_dev": float(rel.max()),
                     "median_rel_dev": float(np.median(rel)),
                     "spearman": float(spearmanr(mine, theirs).statistic)}
    G_E233 = {**e233_vals,
              "disclosed_precision": "CPU/GPU texture tier: Spearman "
                                     ">= 0.99, median rel <= 2%, max <= 5%",
              "pass": bool(e233_vals["spearman"] is not None
                           and e233_vals["spearman"] >= 0.99
                           and e233_vals["median_rel_dev"] <= 0.02
                           and e233_vals["max_rel_dev"] <= 0.05) or SMOKE}
    step_rels = []
    mom_rels = {"m": [], "v": []}
    for w in WASHES:
        for t in range(1, STEPS + 1):
            row = journal[w]["steps"][str(t)]
            if row["applied_norm_live"] > 0:
                step_rels.append(abs(row["applied_norm_rec"]
                                     - row["applied_norm_live"])
                                 / row["applied_norm_live"])
        for st, rcd in (journal.get(w, {}).get("arch_reads", {})
                        or {}).items():
            mom_rels["m"].append(rcd["moment_cert"]["rel_m_max"])
            mom_rels["v"].append(rcd["moment_cert"]["rel_v_max"])
    G_STEP = {"max_rel_dev_rec_vs_live": float(max(step_rels, default=0.0)),
              "tol": 1e-3,
              "pass": bool(max(step_rels, default=0.0) <= 1e-3) or SMOKE}
    G_MOMENT = {"max_rel_m": float(max(mom_rels["m"], default=0.0)),
                "max_rel_v": float(max(mom_rels["v"], default=0.0)),
                "tol": 1e-4,
                "pass": bool(max(mom_rels["m"], default=0.0) <= 1e-4
                             and max(mom_rels["v"], default=0.0) <= 1e-4
                             ) or SMOKE}
    metrics["gates"].update({"G_STEP": G_STEP, "G_MOMENT": G_MOMENT,
                             "G_E233": G_E233})

    # the fp16 floor disclosure
    metrics["reads"] = {
        "z_pool_curves": {"d": z_pool["d"], "dr": z_pool["dr"],
                          "g": z_pool["g"], "t": tsteps},
        "z_per_wash": {w: z_curves[w] for w in WASHES},
        "z_meanof_coreach": z_meanof,
        "md_pool": md_pool,
        "z_majority_fate_coreach": maj,
        "z_at_80": z_at80,
        "perm_checks": perm_checks,
        "fate_overlap_structure": overlap_disc,
        "fp16_floor_over_min_sigma": float(5e-4 / sd54_min) if sd54_min > 0
        else None,
        "min_sd54": float(sd54_min),
        "vhot_examples": {w: {st: rcd["vhot_share"]
                              for st, rcd in
                              (journal.get(w, {}).get("arch_reads", {})
                               or {}).items()} for w in WASHES},
        "pooling_disclosure": "the fixed-effects pool treats the three "
                              "washes as independent; the probes (and "
                              "hence their contrasts) are shared across "
                              "washes — the mean-of-z and majority-fate "
                              "54-value co-reports do not inflate under "
                              "that dependence",
    }

    metrics["predictions"] = {
        "(a) e179 timescale": pred_a,
        "(b) FQ3 pace co-read": {"table": pace_table,
                                 "co_moves_within_10pct": pace_co_moves,
                                 "clause": "T139's pace clause: uniform "
                                 "per-coordinate sign-step (~lr*sqrt(N)); "
                                 "the clock clause: ||Delta|| ~ "
                                 "lr*||d||"},
        "(c) w2 sign replication": pred_c,
    }

    booleans = {
        "h_fossil_window_min_z_ge_2": b_fossil,
        "h_transient_all_mid_lt_1_and_early_ge_2": b_transient,
        "n_late_steps_with_z_ge_2": n_late_ge2,
        "late_window_min_z": float(min(late_z)),
        "mid_window_max_z": float(max(mid_z)),
        "early_window_max_z": float(max(early_z)),
    }
    metrics["adjudication"] = {
        "verdict": (verdict + " (SMOKE — not adjudicated)") if SMOKE
        else verdict,
        "bars_verbatim": REGISTERED["bars_verbatim"],
        "booleans": booleans,
        "per_wash": per_wash_verdicts,
        "contingency": contingency,
        "intervention_leg": ("UNLOCKS (dispatch separately: one "
                             "moment-only step from +80)"
                             if verdict == "H-FOSSIL" and not SMOKE
                             else "locked (verdict != H-FOSSIL)"),
        "windows": {"late": LATE_WINDOW, "mid": MID_WINDOW,
                    "early": EARLY_WINDOW},
        "gated_on": "G_ENV/G_SIZE/G_CORPUS/G_BATT/G_SUPPORT/G_CE/G_DRAWS/"
                    "G_REPLAY/G_MOMENT/G_STEP/G_E233",
        "all_gates_pass": bool(all(
            metrics["gates"][g].get("pass", False)
            for g in ("G_SIZE", "G_CORPUS", "G_BATT", "G_SUPPORT", "G_CE",
                      "G_DRAWS", "G_STEP", "G_MOMENT", "G_E233"))
        ) or SMOKE,
    }

    # ------------------------------------------------ P7 the plots
    verdict_line = (
        f"{verdict} — pooled z(d_t): late-window min {min(late_z):+.2f} "
        f"({n_late_ge2}/{len(LATE_WINDOW)} steps >= 2), by-+40 max "
        f"{max(mid_z):+.2f}; supply echo z(g_80) "
        f"{z_pool['g'][-1]:+.2f}")
    pngs = []
    pngs.append(str(plot_decay(rd, tsteps, z_pool["d"], z_pool["dr"],
                               z_pool["g"],
                               {w: z_curves[w]["d"] for w in WASHES},
                               verdict_line)))
    pngs.append(str(plot_distributions(rd, probes54, fates, journal,
                                       z_at80)))
    if not SMOKE:
        pngs.append(str(plot_validation(rd, journal, e233_ledger, ce_dev)))
    metrics["plot_outputs"] = pngs

    metrics["honesty_reflex"] = {
        "n": "1 organism (GPT-2 124M), 3 washes; ~26-29 killed / 25-28 "
             "living per wash — nothing guaranteed; the GRADED "
             "discipline applies",
        "reconstruction": "the moments are RE-DERIVED from the "
                          "regenerated certified gradients (the e234 "
                          "memmaps were deleted on DONE); the recursion "
                          "matches the live optimizer at machine "
                          "precision (G_MOMENT/G_STEP) and the applied "
                          "trajectory matches e233's committed GPU "
                          "product at the texture tier (G_E233)",
        "correlational": "the contrast is an observational read on "
                         "reconstructed state; the causal test is the "
                         "intervention leg, locked behind H-FOSSIL",
        "supply_echo": "z(g_t) is the interpretation reference: a fossil "
                       "is z_d OVER the supply's echo, not merely z_d — "
                       "the registered bars speak on z_d alone (no bar "
                       "moved)",
        "supports_t0_fixed": "supports are t=0-fixed; they rotate "
                             "~18-20 deg through the wash (e239) — the "
                             "fate-blind tide, disclosed",
        "fp16_floor": f"the support cache's fp16 cos floor ~5e-4 vs the "
                      f"smallest cross-probe sigma {sd54_min:.1e} "
                      f"(ratio {5e-4 / sd54_min if sd54_min > 0 else float('nan'):.3f})",
        "fates_provenance": "labels from e234's committed journal "
                            "trajectories (e214-gated), frozen before "
                            "compute",
        "hot_set": "e226's ladder (k=2000 primary) — the g11 "
                   "shared-hot-set guard is the sd54 null + the "
                   "permutation checks + the overlap disclosure",
        "first_order": "the reads are geometric (direction alignments); "
                       "behavioral fate labels are externally committed",
    }
    metrics["trims"] = []
    metrics["deviations"] = deviations
    metrics["compute"] = {"wall_s": round(time.time() - T0, 1),
                          "device": "CPU only", "threads": THREADS,
                          "load_checks": len(load_checks)}

    # ------------------------------------------------ done
    metrics["status"] = ("DONE (SMOKE — nothing adjudicated)" if SMOKE
                         else "DONE")
    write_metrics(metrics["status"])
    save_journal(rd, journal)
    if not SMOKE:
        import gc
        import shutil
        try:                       # Windows: close the memmap handle first
            sup["mm"].flush()
            sup["mm"]._mmap.close()
        except Exception:                              # noqa: BLE001
            pass
        sup.pop("mm", None)
        gc.collect()
        shutil.rmtree(SCRATCH, ignore_errors=True)
        log(f"scratch cache deleted on DONE: {SCRATCH}")
    log(f"E240 {metrics['status']} — verdict {verdict}; "
        f"wall {time.time() - T0:.0f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
