"""E254 — FQ12, THE V-SPAN OVERLAP (the R64 ideator's Rank 1; the
anti-substrate's mechanism candidate; dispatched 2026-10-04; desk/CPU).

THE QUESTION (verbatim from the dispatch): is the wash-span unwritable
for installs BECAUSE v is large there — Adam's denominator suppressing
every write the corpus work already owns — so "new memories need
orthogonal room" is really "new memories need LOW-V ROOM"?

BARS VERBATIM (frozen from the dispatch BEFORE this script or any
compute; adjudicate against exactly this; no bar shopping):
  - V-ENRICHED — "the span carries >= 3x the random-subspace v-mass
    (sustained across states) — the unwritability gains its mechanism
    candidate: the optimizer's denominator owns the span (H-iii for
    T226); 'new memories need low-v room'"
  - V-FLAT — "the span's v-mass sits within the random band — the
    optimizer exonerated; the unwritability stays interference/
    rank-shaped; the registered rank-matched-random cell adjudicates
    alone"
  - MIXED — "the tables verbatim (per state, per k), no inflation"

OPERATIONALIZATIONS (frozen here BEFORE compute; they fix the clauses,
they do not move the bars):
  * RECONSTRUCTION: e240's fp64 AdamW second-moment recursion re-run on
    the certified wash replay (module-import of e240's own machinery:
    organism, batteries, supports, certification blocks; e240's exact
    chunk loop statements, same order — the recursion is bit-identical
    by construction and certified so). PRIMARY v is over the CLIPPED
    gradients (what the wash's AdamW drank — e240's primary); the
    RAW-gradient flavor v2 co-reported at the archived states. The
    validation stack, re-run here: G_MOMENT (v/m vs the LIVE optimizer,
    elementwise, every archived state), G_STEP (reconstructed
    applied-step norm vs live per step), G_CE (bit-exact CE + raw gnorm
    vs e234's committed journal — the certified gradient cache,
    re-derived), G_DRAWS (bit-exact generator state vs the archived
    *_latest), G_REPLAY (drift vs the archived checkpoints), G_E233 (w1
    applied-norm trajectory vs e233's committed C-arm ledger), G_VHOT
    (this cell's vhot read vs e240's committed journal vhot at every
    archived state — the direct re-validation against e240's committed
    numbers).
  * THE SPAN BASIS: e234's committed split-half basis, RE-DERIVED from
    the committed journal's gram_scaled_* + journaled raw gnorms (the
    exact matrices e234 decomposed — pure committed-data linear algebra,
    verified against e234's committed spectrum/knee/coverage in
    G_BASIS). The basis is never materialized in R^N: every read is a
    cA-weighted dot over the first-half gradient rows. The first-half
    RAW pre-clip gradients themselves are REGENERATED by the
    deterministic replay into an fp16 memmap (e234's cache convention:
    L2-normalized x 2^14 + journaled true norms); the regenerated Gram
    is certified against the committed gram_scaled in G_GRAM (fp16
    cache tier).
  * THE READ (the registered bar): v's mass on the wash-span directions
    := the squared-L2 projection energy fraction ||P_k v_t||^2/||v_t||^2
    of the reconstructed second moment onto the top-k span basis. NULL:
    n=20 fresh random-subspace draws per read (each draw: K_MAX=20
    fresh gaussian vectors over all N coords, generated chunk-wise from
    disclosed per-(seed, chunk) PCG streams, fp32 generation with fp64
    algebra; the k-subspace = the span of the leading k vectors, the
    exact orthonormalized projection d^T R^{-1} d via the Gram inverse —
    nothing materialized). Enrichment(state, k) = span_mass/null_mean.
    States = the states e240 VALIDATED the recursion at (its G_MOMENT
    archived states): w1 {2, 10, 50, 80} (PRIMARY — the bit-exact
    CPU-origin wash); w2/w3 {10, 50, 80} (replication co-report, the
    disclosed GPU-fp32-origin texture tier). k-ladder {1, 2, 5, 10, 20};
    the primary k = the committed knee kA = 2.
  * ADJUDICATION (order V-ENRICHED -> V-FLAT -> MIXED; primary = w1,
    k = 2, all four archived states): "sustained across states" :=
    enrichment >= 3 at EVERY archived state. "within the random band"
    := span_mass <= the draws' max at EVERY archived state. Everything
    else = MIXED, tables verbatim.
  * CO-READ 1 (the fact battery, e240's vhot convention reproduced):
    v's L1 mass on the fact battery's hot-coordinate sets (top-|s_i|
    per fact probe, union over the 20 fact probes; e226's ladder k_hot
    2000/20000/200000) vs random coordinate sets of the same size
    (n=20 fresh draws) — the per-coordinate companion to the
    direction-level primary.
  * CO-READ 2 (the t=0 v-map): the pretraining's v is NOT reconstructable
    and is NOT in the wash's v at any state (v_0 = 0 exactly — the wash
    starts from a FRESH optimizer state; disclosed). What the wash's own
    history gives: the span-mass curve over t (grid {1,2,3,5,10,20,30,
    40,50,60,70,80}, w1) with TWO supply references — the instantaneous
    squared-gradient's span mass (the exact supply of v_t; g_t stashed
    fp32 at grid steps, dots post-hoc) and the gradient-ENERGY flavor
    (||P g_t||^2/||g_t||^2, computable for ALL t from the committed
    Gram). v's curve read OVER these references separates "the span is
    v-heavy because the supply writes it every step" from "the EMA
    concentrates beyond the instantaneous supply" (T225's amplifier
    texture). Internal consistency: at t=1, v_1 = (1-b2)*(clip*g_1)^2 —
    a pure rescaling of g_1^2 — so the v curve and the squared-supply
    curve MUST coincide at t=1 (checked, disclosed).
  * DISCLOSED INSTRUMENT RISK (frozen before compute): v is BUILT from
    the wash's own squared gradients and the span is BUILT from the
    wash's own gradients — the random-subspace null is the registered
    instrument and the bar speaks on it alone, but a large enrichment is
    arithmetically pre-announced; the interpretation layer (the two
    supply references + the fact-hot read) carries the mechanism reading
    and is reported verbatim regardless of the verdict. No bar shopping.

GATES: G_ENV (CPU-only, torch threads 8 = e182c's bit-exact replay
convention, BLAS 4; psutil load checks per phase; RAM wait-floors
before the memmap/snapshot phases — e252 is co-running on CPU,
load-polite), G_SIZE, G_CORPUS, G_BATT, G_SUPPORT, G_CE, G_DRAWS,
G_REPLAY, G_MOMENT, G_STEP, G_E233, G_VHOT, G_BASIS, G_GRAM.

PROVENANCE (extend-don't-repeat): builds on the dispatch brief (FQ12,
scratch/review_r64_ideator.md's Rank 1), T226/e246 (the anti-substrate:
ALIGNED installs express nothing, ORTHO lands; H-i/H-ii and the
registered rank-matched-random discriminator), T225/e240 (the amplifier;
v's mass on the LIVING hot sets; the fact coords' 1.10-1.38x pace; THE
fp64 v-reconstruction machinery this cell module-imports), T217/e234
(the committed wash-span bases + the certified gradient caches'
provenance; the split-half conventions), T198/e226 (the support bank,
the cache conventions, the hot-set ladder), e233 (the C-arm applied-step
ledger), e182c/e182c2/e217 (the three-wash archive + certified draw
streams). NEW: the first read of the optimizer's second moment AGAINST
the wash-span basis (the direction-level v-map); the matched
random-subspace null for moment mass; the supply-reference curves; the
fact-hot coordinate companion.

Envelope: CPU-only, torch threads 8, progressive PARTIAL metrics +
journal after every phase, load checks per phase, scratch memmaps
deleted on DONE / kept on failure. No NOTES/THINKING/QUEUE/STATE edits
(dispatch). Smoke via E254_SMOKE=1 (12 steps, w1 only, the basis from
the regenerated 6x6 block, k-ladder {1,2}, 4 null seeds; nothing
adjudicated or gated).

Run:  cd lab && python e254_vspan_overlap.py     (E254_SMOKE=1 for the
      shakedown; nothing adjudicated or gated in smoke)
"""
from __future__ import annotations

import copy
import gc
import json
import math
import os
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

# import e240 FIRST: it sets the offline/env/thread defaults before
# numpy/torch load (its module-level block is configuration only).
import e240_moment_archive as e240              # noqa: E402 — the machinery

import numpy as np                              # noqa: E402
import torch                                    # noqa: E402

import common                                   # noqa: E402
from common import now_iso, run_dir, save_json  # noqa: E402

e1 = e240.e1                                    # e182c, via e240
e226 = e240.e226                                # via e240

import torch.nn.functional as F                 # noqa: E402
from scipy.stats import spearmanr               # noqa: E402

import matplotlib                                # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt                 # noqa: E402
import textwrap                                  # noqa: E402

try:
    import psutil                               # noqa: E402
except ImportError:
    psutil = None

SMOKE = os.environ.get("E254_SMOKE") == "1"
CPU = torch.device("cpu")
NAME = "e254_smoke" if SMOKE else "e254"

T0 = time.time()
_log_t0 = time.time()
def log(m: str) -> None:
    print(f"[{time.time() - _log_t0:8.1f}s] {m}", flush=True)

# ------------------------------------------------------------ the frozen cell
WASHES = ("w1",) if SMOKE else ("w1", "w2", "w3")
PRIMARY_WASH = "w1"
STEPS = 12 if SMOKE else 80
HALF = STEPS // 2                                 # the split-half boundary
KNEE_MAX_I = 5 if SMOKE else 20                   # e234's knee search head
K_CAP = 2 if SMOKE else 20                        # e234's cap (knee <= 20)
K_LADDER = (1, 2) if SMOKE else (1, 2, 5, 10, 20) # the read's k ladder
K_PRIMARY = 2                                     # the committed knee kA
N_NULL_DRAWS = 4 if SMOKE else 20                 # >= 20 per the spec
K_NULL_MAX = 2 if SMOKE else 20                   # gaussian vectors/draw
NULL_SEED_BASE = 2_540_000                        # disclosed
NULL_SEED_STRIDE = 1_000_003                      # disclosed
NULL_CHUNK_STRIDE = 7919                          # disclosed
CHUNK_NULL = 1 << 21                              # 2^21 coords/null chunk
ARCH_STATES = {"w1": (2, 10, 50, 80) if not SMOKE else (2, 10),
               "w2": (10, 50, 80), "w3": (10, 50, 80)}
CURVE_GRID = ((1, 2, 3, 5, 8, 10, 12) if SMOKE else
              (1, 2, 3, 5, 10, 20, 30, 40, 50, 60, 70, 80))  # w1 only
CACHE_SCALE = e226.CACHE_SCALE                    # 2**14
CHUNK = e240.CHUNK                                # 2**22 (e226/e240 chunk)
K_LADDER_HOT = e226.K_LADDER                      # (2000, 20000, 200000)
RAM_FLOOR_GB = e240.RAM_FLOOR_GB                  # 16 (e226's cache floor)
RAM_FLOOR_NULL_GB = 12.0                          # snapshot phase (disclosed)
LR, B1, B2, WD, EPS_ADAM, CLIP = (e240.LR, e240.B1, e240.B2,
                                  e240.WD, e240.EPS_ADAM, e240.CLIP)
SCRATCH = common.REPO / "scratch" / "e254_cache"

# committed records (load-only)
E226_M = common.REPO / "runs" / "e226" / "metrics.json"
E233_M = common.REPO / "runs" / "e233" / "metrics.json"
E234_M = common.REPO / "runs" / "e234" / "metrics.json"
E234_J = common.REPO / "runs" / "e234" / "journal.json"
E240_M = common.REPO / "runs" / "e240" / "metrics.json"
E240_J = common.REPO / "runs" / "e240" / "journal.json"

REGISTERED = {
    "bars_verbatim": {
        "V-ENRICHED": "the span carries >= 3x the random-subspace v-mass "
        "(sustained across states) — the unwritability gains its mechanism "
        "candidate: the optimizer's denominator owns the span (H-iii for "
        "T226); 'new memories need low-v room'",
        "V-FLAT": "the span's v-mass sits within the random band — the "
        "optimizer exonerated; the unwritability stays interference/"
        "rank-shaped; the registered rank-matched-random cell adjudicates "
        "alone",
        "MIXED": "the tables verbatim (per state, per k), no inflation",
    },
    "question_verbatim": "is the wash-span unwritable for installs BECAUSE "
    "v is large there — Adam's denominator suppressing every write the "
    "corpus work already owns — so 'new memories need orthogonal room' is "
    "really 'new memories need LOW-V ROOM'?",
    "registration": "bars + question frozen VERBATIM from the dispatch "
    "brief (frozen BEFORE this script or any compute); adjudicate against "
    "exactly this; no bar shopping",
}

deviations: list[str] = [
    "The e234/e240 gradient caches were deleted on those cells' DONE "
    "(their disclosed lifecycles); the certified gradients are REGENERATED "
    "here by the identical deterministic replay (module-import of e240's "
    "machinery), and the first-half RAW pre-clip gradients are stored as "
    "an fp16 memmap in e234's cache convention (normalized x 2^14 + "
    "journaled true norms) — deleted after each wash's reads, kept on any "
    "failure for post-mortem.",
    "The span basis is re-derived from e234's COMMITTED journal Gram "
    "(gram_scaled_* + journaled gnorms — the exact matrices e234 "
    "decomposed); the basis vectors are never materialized in R^N (all "
    "reads are cA-weighted dots). Verified in G_BASIS against e234's "
    "committed spectrum/knee/coverage; the REGENERATED Gram is certified "
    "in G_GRAM at the fp16 cache tier.",
    "PRIMARY v is over the CLIPPED gradients (e240's primary — what the "
    "wash's AdamW drank); the RAW-gradient flavor co-reported at the "
    "archived states.",
    "The primary mass definition is the squared-L2 projection energy "
    "fraction (the frozen operationalization of 'v's mass on the span "
    "directions'); the per-coordinate companion is the fact-hot L1 "
    "co-read (e240's vhot convention).",
    "The random-subspace null uses fresh gaussian draws (fp32 generation, "
    "fp64 algebra) orthonormalized in closed form via the Gram inverse "
    "(exact projection, nothing materialized); per-(seed, chunk) PCG "
    f"streams with disclosed seeds (base {NULL_SEED_BASE}, stride "
    f"{NULL_SEED_STRIDE}, chunk stride {NULL_CHUNK_STRIDE}).",
    "The supports memmap is deleted immediately after certification + "
    "hot-set extraction (nothing downstream reads it — this cell reads no "
    "probe alignments; the RAM is released for the replay phase; "
    "disclosed).",
    "The t=0 v-map DISCLOSES: v_0 = 0 exactly (fresh optimizer state); "
    "the pretraining's v is not reconstructable and not in the wash's v "
    "at any state; the curve reads the wash's own history only. The "
    "t=1 identity (v_1 = pure rescaling of g_1^2, so the v curve and "
    "the squared-supply curve coincide at t=1) is checked as an internal "
    "consistency read.",
    "No NOTES/THINKING/QUEUE/STATE edits (dispatch).",
    "Smoke mode (E254_SMOKE=1): 12 steps, w1 only, the basis from the "
    "regenerated 6x6 block (knee head 5), k-ladder {1,2}, 4 null seeds; "
    "nothing adjudicated or gated (SMOKE stamp).",
]


# ------------------------------------------------------------ envelope

def cpu_load_check(tag: str) -> dict:
    if psutil is None:
        return {"tag": tag, "psutil": "absent"}
    rec = {"tag": tag,
           "cpu_percent": psutil.cpu_percent(interval=0.5),
           "ram_avail_gb": round(psutil.virtual_memory().available / 2**30, 1)}
    log(f"  [load] {tag}: cpu {rec['cpu_percent']}% "
        f"ram_avail {rec['ram_avail_gb']} GB")
    return rec


def ram_wait(floor_gb: float, tag: str, max_wait_s: float = 600.0) -> dict:
    """e234's RAM wait-loop (load-polite to e252, the co-running CPU cell)."""
    if psutil is None:
        return {"tag": tag, "psutil": "absent"}
    t0 = time.time()
    while psutil.virtual_memory().available / 2**30 < floor_gb:
        if time.time() - t0 > max_wait_s:
            log(f"  [ram-wait] {tag}: floor {floor_gb} GB NOT reached in "
                f"{max_wait_s}s — proceeding anyway (disclosed)")
            return {"tag": tag, "waited_s": round(time.time() - t0, 1),
                    "floor_gb": floor_gb, "cleared": False}
        time.sleep(20)
    return {"tag": tag, "waited_s": round(time.time() - t0, 1),
            "floor_gb": floor_gb, "cleared": True}


def save_journal(rd: Path, journal: dict):
    (rd / "journal.json").write_text(
        json.dumps(journal, indent=1, default=float), encoding="utf-8")


# ------------------------------------------------------------ basis algebra

def true_gram(G_scaled: np.ndarray, gnorms: np.ndarray) -> np.ndarray:
    """e234's decompose() Gram math VERBATIM: scaled-unit Gram -> true-unit
    raw-gradient Gram (rows reweighted by journaled norms, /2^28)."""
    S = G_scaled.shape[0]
    Gn = G_scaled.copy()
    for t in range(S):
        Gn[t] *= gnorms[t]
        Gn[:, t] *= gnorms[t]
    Gn /= float(CACHE_SCALE ** 2)
    return Gn


def basis_coeffs(Gn: np.ndarray, half: int, knee_max_i: int, cap: int):
    """e234's basis_of VERBATIM on the first-half block: the knee-k top
    eigenvectors, coefficient columns orthonormalized by 1/sqrt(lambda).
    Returns (k, cA_k, evec, evals_desc, meta)."""
    ev, evec = np.linalg.eigh(Gn[:half, :half])
    order = np.argsort(ev)[::-1]
    ev, evec = ev[order], evec[:, order]
    gaps = [(float(ev[i - 1] - ev[i]), i + 1)
            for i in range(1, min(knee_max_i, len(ev) - 1) + 1)]
    k = max(gaps)[1] if gaps else 1
    capped = False
    if k > cap:
        k, capped = cap, True
    c = evec[:, :k] / np.sqrt(np.clip(ev[:k], 1e-12, None))
    meta = {"spectrum": ev.tolist(), "knee_k": int(k), "k_capped": capped,
            "var_frac_at_k": float(ev[:k].sum() / ev.sum()) if ev.sum() > 0
            else None, "gaps": [g for g, _ in gaps]}
    return k, c, evec, ev, meta


def coverage_median(Gn: np.ndarray, gnorms: np.ndarray, cA: np.ndarray,
                    half: int) -> float:
    """e234's coverage_A median: the fraction of each SECOND-half step's
    squared L2 inside the first-half basis (from the Gram alone)."""
    B_A = cA.T @ Gn[:half, half:]                # (k, S-half)
    wind2 = np.einsum("ij,ij->j", B_A, B_A)
    return float(np.median(wind2 / (gnorms[half:] ** 2)))


def ladder_from(evec: np.ndarray, evals: np.ndarray) -> dict:
    """The k-ladder of coefficient matrices (columns orthonormalized)."""
    return {k: evec[:, :k] / np.sqrt(np.clip(evals[:k], 1e-12, None))
            for k in K_LADDER}


# ------------------------------------------------------------ the replay

def replay_wash(net0, train_ids, sup, journal, w: str, e234_wj,
                snap_states, stash_states):
    """One wash replayed with e240's VERBATIM arithmetic (its chunk-loop
    statements, same order — the m_/v_ recursions are bit-identical by
    construction), extended with: (a) the first-half RAW pre-clip
    gradients streamed to an fp16 memmap (e234's cache convention);
    (b) fp64 v snapshots at the read states (+ v2 snapshots fp32 at the
    archived states); (c) g_t stashed fp32 at the curve grid (w1 — the
    supply reference); (d) the vhot read + the live-optimizer moment
    certification at the archived states."""
    S = STEPS
    N = sum(p.numel() for p in net0.parameters())
    wj = journal.setdefault(w, {"steps": {}})
    arch = ARCH_STATES[w]
    probes54 = sup["probes54"]

    SCRATCH.mkdir(parents=True, exist_ok=True)
    gm_path = SCRATCH / f"grads_{w}.npy"
    gm = np.lib.format.open_memmap(gm_path, mode="w+", dtype=np.float16,
                                   shape=(HALF, N))

    net = copy.deepcopy(net0)
    net.train()
    opt = torch.optim.AdamW(net.parameters(), lr=LR, betas=(B1, B2),
                            weight_decay=WD)
    gen = torch.Generator().manual_seed(e240.W_SEED[w])
    hi = train_ids.shape[0] - e1.SEQ - 1

    m_ = torch.zeros(N, dtype=torch.float64)        # e240's m_ (clipped)
    v_ = torch.zeros(N, dtype=torch.float64)        # PRIMARY v (clipped)
    v2_ = torch.zeros(N, dtype=torch.float64)       # RAW flavor
    snaps, snaps2, g_stash = {}, {}, {}
    vhot_mine, moment_certs = {}, {}
    t_start = time.time()

    for step in range(1, S + 1):
        off = torch.randint(hi, (e1.BATCH,), generator=gen)
        x = torch.stack([train_ids[o: o + e1.SEQ] for o in off])
        y = torch.stack([train_ids[o + 1: o + 1 + e1.SEQ] for o in off])
        logits = net(input_ids=x).logits
        loss = F.cross_entropy(logits.reshape(-1, logits.shape[-1]),
                               y.reshape(-1))
        ce = float(loss.item())
        opt.zero_grad(set_to_none=True)
        loss.backward()
        g_raw = e226.flat_grad(net)                     # fp32 flat
        nrm = float(g_raw.norm(dtype=torch.float64).item())
        if not (nrm > 0 and math.isfinite(nrm)):
            raise RuntimeError(f"{w} s{step}: degenerate gradient")
        g_st = g_raw.clone() if (w == PRIMARY_WASH
                                 and step in stash_states) else None
        tn = torch.nn.utils.clip_grad_norm_(net.parameters(), CLIP)
        tnf = float(tn)
        clip_fac = min(1.0, 1.0 / (tnf + 1e-6))         # torch's formula

        pb = [p.detach().clone() for p in net.parameters()]
        theta_b = torch.cat([t.reshape(-1) for t in pb])

        b1c = 1.0 - B1 ** step
        b2c = 1.0 - B2 ** step
        d2 = arec = 0.0
        inv = 1.0 / nrm
        for a in range(0, N, CHUNK):
            b = min(a + CHUNK, N)
            raw64 = g_raw[a:b].to(torch.float64)
            gc64 = raw64 * clip_fac
            # e240's VERBATIM recursion statements (same order/chunking)
            m_[a:b].mul_(B1).add_(gc64, alpha=1.0 - B1)
            v_[a:b].mul_(B2).addcmul_(gc64, gc64, value=1.0 - B2)
            v2_[a:b].mul_(B2).addcmul_(raw64, raw64, value=1.0 - B2)
            d = (m_[a:b] / b1c) / ((v_[a:b] / b2c).sqrt() + EPS_ADAM)
            d2 += float(d.dot(d))
            arec += float((WD * theta_b[a:b].to(torch.float64) + d
                           ).pow(2).sum())
            if step <= HALF:   # cache the RAW pre-clip row (e234's conv.)
                row = ((raw64 * inv) * CACHE_SCALE).to(torch.float16)
                gm[step - 1, a:b] = row.numpy()
                del row
            del d, raw64, gc64
        opt.step()
        live2 = 0.0
        with torch.no_grad():
            for p, pbb in zip(net.parameters(), pb):
                live2 += float((p - pbb).pow(2).sum(dtype=torch.float64))
        del pb, theta_b, g_raw

        applied_rec = LR * math.sqrt(max(arec, 0.0))
        applied_live = math.sqrt(max(live2, 0.0))
        wj["steps"][str(step)] = {
            "ce": ce, "gnorm_raw": nrm, "tn_torch": tnf,
            "clip_fac": clip_fac, "applied_norm_rec": applied_rec,
            "applied_norm_live": applied_live,
            "dnorm": math.sqrt(max(d2, 0.0)),
        }

        # ---- G_REPLAY: drift vs the archived checkpoint at its own step
        if not SMOKE and step in e240.W_ARCH[w]:
            wj.setdefault("replay_cert", {})[str(step)] = \
                e240.drift_vs_archived(net, e240.W_ARCH[w][step])

        # ---- archived-state reads: G_MOMENT + the vhot reproduction
        if not SMOKE and step in arch:
            ma = torch.cat([opt.state[p]["exp_avg"].reshape(-1)
                            for p in net.parameters()])
            va = torch.cat([opt.state[p]["exp_avg_sq"].reshape(-1)
                            for p in net.parameters()])
            rel_m = float((m_ - ma.to(torch.float64)).abs().max()
                          / ma.abs().max().clamp(min=1e-30))
            rel_v = float((v_ - va.to(torch.float64)).abs().max()
                          / va.abs().max().clamp(min=1e-30))
            del ma, va
            vsum = float(v_.sum())
            vhot = {}
            for i, pr in enumerate(probes54):
                vhot[pr["fact"]] = {
                    str(k): float(v_[torch.from_numpy(
                        sup["hot_idx"][(i, k)])].sum() / vsum)
                    for k in K_LADDER_HOT}
            moment_certs[str(step)] = {"rel_m_max": rel_m, "rel_v_max": rel_v}
            vhot_mine[str(step)] = vhot

        # ---- snapshots (v fp64 at archived; fp32 at curve extras)
        if step in snap_states:
            snaps[step] = (v_.clone() if step in arch
                           else v_.to(torch.float32).clone())
            if step in arch:
                snaps2[step] = v2_.to(torch.float32).clone()
        if g_st is not None:
            g_stash[step] = g_st

        if step % 10 == 0 or step == S:
            log(f"  [{w} replay] s{step:3d}/{S} CE {ce:.4f} |g| {nrm:.2f} "
                f"clip {clip_fac:.4f} applied {applied_live:.4f} "
                f"({time.time() - t_start:.0f}s)")
            journal[w] = wj
            save_journal(RD, journal)
    gm.flush()

    # ---- G_DRAWS: bit-exact generator state vs the archived *_latest
    gen_ok = None
    if not SMOKE:
        archived = torch.load(e240.W_LATEST[w], map_location=CPU,
                              weights_only=False)["gen"]
        gen_ok = bool(torch.equal(gen.get_state(), archived))

    # ---- G_CE: bit-exact vs e234's journaled CE + gnorms
    ce_cert = gnorm_cert = None
    if e234_wj is not None:
        ce_cert = max(abs(wj["steps"][str(t)]["ce"] - e234_wj["ces"][t - 1])
                      for t in range(1, S + 1))
        gnorm_cert = max(abs(wj["steps"][str(t)]["gnorm_raw"]
                             - e234_wj["gnorms"][t - 1])
                         for t in range(1, S + 1))

    # ---- the squared norms of every snapshot/stash (mass denominators)
    snap_norms = {st: float(s.double().pow(2).sum().item())
                  for st, s in snaps.items()}
    snap2_norms = {st: float(s.double().pow(2).sum().item())
                   for st, s in snaps2.items()}
    stash_norms = {}
    for st, g in g_stash.items():
        g64 = g.double()
        g2 = g64 * g64
        stash_norms[st] = float(g2.dot(g2).item())
        del g64, g2

    out = {"gen_ok": gen_ok, "ce_cert": ce_cert, "gnorm_cert": gnorm_cert,
           "replay_cert": wj.get("replay_cert", {}),
           "moment_certs": moment_certs, "vhot_mine": vhot_mine,
           "snaps": snaps, "snaps2": snaps2, "g_stash": g_stash,
           "snap_norms": snap_norms, "snap2_norms": snap2_norms,
           "stash_norms": stash_norms, "gm_path": gm_path, "gm": gm}
    journal[w] = wj
    save_journal(RD, journal)
    log(f"{w}: replay done ({time.time() - t_start:.0f}s); gen_ok {gen_ok}; "
        f"dCE {ce_cert}; dgnorm {gnorm_cert}")
    return out


# ------------------------------------------------------------ post-replay reads

def gram_from_memmap(gm) -> np.ndarray:
    """The regenerated scaled-unit Gram (e234's gram_and_dots math)."""
    s = gm.shape[0]
    G = np.zeros((s, s), dtype=np.float64)
    N = gm.shape[1]
    for a in range(0, N, CHUNK):
        b = min(a + CHUNK, N)
        C = np.asarray(gm[:, a:b], dtype=np.float64)
        G += C @ C.T
    return G


def dots_vs_cache(gm, gnorms_half: np.ndarray, x: torch.Tensor) -> np.ndarray:
    """<g_s, x> for s = 1..HALF in TRUE units, from the fp16 cache rows +
    journaled norms (x a full-length fp32/fp64 tensor)."""
    N = gm.shape[1]
    out = np.zeros(HALF, dtype=np.float64)
    inv_scale = 1.0 / CACHE_SCALE
    for a in range(0, N, CHUNK):
        b = min(a + CHUNK, N)
        C = torch.from_numpy(
            np.ascontiguousarray(gm[:, a:b])).to(torch.float64)
        out += (C @ x[a:b].to(torch.float64)).numpy()
        del C
    return out * (gnorms_half * inv_scale)


def span_masses(gdotv: np.ndarray, xnorm2: float, cA_ladder: dict) -> dict:
    """||P_k v||^2/||v||^2 per k in the ladder."""
    out = {}
    for k, cA in cA_ladder.items():
        proj = cA.T @ gdotv
        out[k] = float(proj @ proj / xnorm2) if xnorm2 > 0 else float("nan")
    return out


def null_sweep(states_by_wash: dict, snaps_by_wash: dict,
               norms_by_wash: dict, N: int) -> dict:
    """THE RANDOM-SUBSPACE NULL: fresh gaussian-subspace draws; per draw
    K_NULL_MAX gaussian vectors over all N coords from disclosed
    per-(seed, chunk) PCG streams (fp32 generation, fp64 algebra); the
    exact orthonormalized projection d^T R^{-1} d via the Gram inverse.
    Returns {(wash, state, k): np.ndarray(n_draws)}."""
    keys = [(w, st) for w in states_by_wash for st in states_by_wash[w]]
    draws = {(w, st, k): np.zeros(N_NULL_DRAWS)
             for w, st in keys for k in K_LADDER}
    t0 = time.time()
    for di in range(N_NULL_DRAWS):
        seed = NULL_SEED_BASE + NULL_SEED_STRIDE * di
        R = np.zeros((K_NULL_MAX, K_NULL_MAX), dtype=np.float64)
        d = {(w, st): np.zeros(K_NULL_MAX, dtype=np.float64)
             for w, st in keys}
        for ci, a in enumerate(range(0, N, CHUNK_NULL)):
            b = min(a + CHUNK_NULL, N)
            g = torch.Generator().manual_seed(
                seed + NULL_CHUNK_STRIDE * ci)
            Z = torch.randn(K_NULL_MAX, b - a, generator=g,
                            dtype=torch.float32).to(torch.float64).numpy()
            R += Z @ Z.T
            for w, st in keys:
                d[(w, st)] += Z @ snaps_by_wash[w][st][a:b].to(
                    torch.float64).numpy()
            del Z
        for w, st in keys:
            vnorm2 = norms_by_wash[w][st]
            for k in K_LADDER:
                dk = d[(w, st)][:k]
                Rk = R[:k, :k]
                draws[(w, st, k)][di] = float(
                    dk @ np.linalg.solve(Rk, dk)) / vnorm2
        if (di + 1) % 5 == 0 or di == N_NULL_DRAWS - 1:
            log(f"  [null] draw {di + 1}/{N_NULL_DRAWS} "
                f"({time.time() - t0:.0f}s)")
    return draws


def fact_hot_read(snaps: dict, fact_masks: dict) -> dict:
    """v's L1 share on the fact battery's hot-coordinate sets vs random
    coordinate sets of the same size (n draws)."""
    N = len(fact_masks[K_LADDER_HOT[0]])
    out = {}
    for st, v in snaps.items():
        v64 = v.to(torch.float64)
        tot = float(v64.sum())
        for k_hot, mask in fact_masks.items():
            size = int(mask.sum())
            share = float(v64[torch.from_numpy(mask)].sum() / tot)
            rng = np.random.default_rng(3_254_000 + k_hot + 97 * st)
            rand = np.empty(N_NULL_DRAWS)
            for i in range(N_NULL_DRAWS):
                idx = rng.choice(N, size=size, replace=False)
                rand[i] = float(v64[torch.from_numpy(idx)].sum() / tot)
            out[(st, k_hot)] = {
                "fact_share": share, "random_mean": float(rand.mean()),
                "random_min": float(rand.min()),
                "random_max": float(rand.max()),
                "enrichment": share / float(rand.mean())
                if rand.mean() > 0 else float("nan"),
                "n_coords": size}
        del v64
    return out


# ------------------------------------------------------------ plots

def plot_enrichment(rd, tables, verdict_line):
    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    ax = axes[0]
    rows = [t for t in tables if t["wash"] == PRIMARY_WASH
            and t["k"] == K_PRIMARY]
    xs = np.arange(len(rows))
    ax.fill_between(xs, [t["null_min"] for t in rows],
                    [t["null_max"] for t in rows],
                    color="#95a5a6", alpha=0.5,
                    label="random-subspace band (20 draws, min..max)")
    ax.plot(xs, [t["null_mean"] for t in rows], "o--", color="#5d6d7e",
            ms=4, lw=1.2, label="random mean (the k/N tier)")
    ax.plot(xs, [t["span_mass"] for t in rows], "D-", color="#8e44ad",
            ms=8, lw=2, label="v_t on the SPAN (reconstructed)")
    for k, c in zip([k for k in K_LADDER if k != K_PRIMARY],
                    ("#c0392b", "#e67e22", "#16a085", "#2c3e50")):
        rr = [t for t in tables if t["wash"] == PRIMARY_WASH and t["k"] == k]
        if rr:
            ax.plot(xs[:len(rr)], [t["span_mass"] for t in rr], ":",
                    color=c, lw=1.1, alpha=0.8, label=f"span, k={k}")
    ax.set_yscale("log")
    ax.set_xticks(xs)
    ax.set_xticklabels([f"t={t['state']}" for t in rows])
    ax.set_ylabel("v-mass fraction (log)")
    ax.set_title("w1 PRIMARY — span v-mass vs the null band "
                 "(k = 2, the committed knee)", fontsize=10)
    ax.legend(fontsize=7.5, loc="center left")
    ax.grid(alpha=0.25, which="both")
    ax = axes[1]
    for wtag, c, mk in zip(("w1", "w2", "w3"),
                           ("#8e44ad", "#c0392b", "#1a6faf"),
                           ("D", "s", "^")):
        rr = [t for t in tables if t["wash"] == wtag and t["k"] == K_PRIMARY]
        if not rr:
            continue
        ax.plot([t["state"] for t in rr], [t["enrichment"] for t in rr],
                mk + "-", color=c, ms=8, lw=1.8, alpha=0.9,
                label=wtag + (" (PRIMARY)" if wtag == PRIMARY_WASH else ""))
    ax.axhline(3.0, color="#c0392b", ls="--", lw=1.5,
               label="the registered 3x bar")
    ax.axhline(1.0, color="0.4", ls=":", lw=1.2, label="parity (1x)")
    ax.set_yscale("log")
    ax.set_xlabel("wash step t (archived states)")
    ax.set_ylabel("enrichment  span_mass / null_mean  (log)")
    ax.set_title("ENRICHMENT RATIOS at k = 2 — per state, per wash",
                 fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25, which="both")
    fig.suptitle("E254 — THE V-SPAN OVERLAP: does Adam's denominator own "
                 "the unwritable span?\n" + textwrap.fill(verdict_line, 118),
                 fontsize=10.5)
    fig.tight_layout(rect=(0, 0, 1, 0.88))
    png = rd / f"{NAME}_enrichment.png"
    fig.savefig(png, dpi=130)
    plt.close(fig)
    return png


def plot_curve(rd, curve, verdict_line):
    fig, ax = plt.subplots(figsize=(9.5, 6))
    t = [c["t"] for c in curve]
    ax.plot(t, [c["span_mass"] for c in curve], "D-", color="#8e44ad",
            ms=6, lw=1.8, label="v_t on the span (k=2)")
    ax.fill_between(t, [c.get("null_min") for c in curve],
                    [c.get("null_max") for c in curve],
                    color="#95a5a6", alpha=0.45,
                    label="random band (the state-free Haar tier)")
    ax.plot(t, [c.get("supply_sq") for c in curve], "s:", color="#e67e22",
            ms=5, lw=1.4, label="SUPPLY echo: g_t^2 on the span")
    ax.plot(t, [c["grad_energy"] for c in curve], "^:", color="#16a085",
            ms=5, lw=1.4,
            label="gradient ENERGY flavor ||P g_t||^2/||g_t||^2")
    ax.set_yscale("log")
    ax.set_xlabel("wash step t (w1)")
    ax.set_ylabel("mass fraction (log)")
    ax.axvline(0.5, color="0.3", lw=1)
    ax.annotate("t=0: v = 0 exactly (fresh optimizer state;\nthe "
                "pretraining's v is NOT reconstructable — disclosed)",
                xy=(0.02, 0.05), xycoords="axes fraction", fontsize=7.5,
                color="0.25")
    ax.set_title("THE t=0 V-MAP (w1) — how early is the span v-heavy, and "
                 "is it more than the supply?", fontsize=10)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.25, which="both")
    fig.suptitle("E254 — the wash's own history\n"
                 + textwrap.fill(verdict_line, 110), fontsize=10)
    fig.tight_layout(rect=(0, 0, 1, 0.9))
    png = rd / f"{NAME}_curve.png"
    fig.savefig(png, dpi=130)
    plt.close(fig)
    return png


def plot_validation(rd, journal_mine, e233_ledger, gram_dev_rows, vhot_rows):
    fig, axes = plt.subplots(1, 4, figsize=(19, 4.8))
    ax = axes[0]
    if "w1" in journal_mine and journal_mine["w1"].get("steps"):
        rec = np.array([journal_mine["w1"]["steps"][str(t)]
                        ["applied_norm_rec"] for t in range(1, STEPS + 1)])
        live = np.array([journal_mine["w1"]["steps"][str(t)]
                         ["applied_norm_live"] for t in range(1, STEPS + 1)])
        ax.scatter(live, rec, s=12, color="#16a085", label="rec vs LIVE")
        lim = [0, max(rec.max(), live.max()) * 1.06]
        ax.plot(lim, lim, "k--", lw=0.8)
        if e233_ledger is not None:
            theirs = np.array([e233_ledger[str(t)]["applied_norm"]
                               for t in range(1, STEPS + 1)])
            ax.scatter(theirs, rec, s=8, color="#c0392b", alpha=0.6,
                       label="rec vs e233 C-arm (GPU)")
        ax.set_xlabel("live / e233 ||step||")
        ax.set_ylabel("reconstructed ||step||")
        rel = np.abs(rec - live) / np.maximum(live, 1e-30)
        ax.set_title(f"G_STEP: max rel {rel.max():.1e}", fontsize=9.5)
        ax.legend(fontsize=7.5)
    ax.grid(alpha=0.25)
    ax = axes[1]
    labels, rm, rv = [], [], []
    for w in ("w1", "w2", "w3"):
        for st, rc in sorted((journal_mine.get(w, {}).get(
                "moment_certs") or {}).items()):
            labels.append(f"{w}:{st}")
            rm.append(rc["rel_m_max"])
            rv.append(rc["rel_v_max"])
    if labels:
        xx = np.arange(len(labels))
        ax.bar(xx - 0.18, rm, 0.36, color="#8e44ad", label="rel |m-m_live|")
        ax.bar(xx + 0.18, rv, 0.36, color="#e67e22",
               label="rel |v-v_live|")
        ax.set_xticks(xx)
        ax.set_xticklabels(labels, fontsize=7, rotation=45)
        ax.set_yscale("log")
    ax.set_title("G_MOMENT: recursion vs live optimizer (archived states)",
                 fontsize=9)
    ax.legend(fontsize=7.5)
    ax.grid(alpha=0.25, axis="y")
    ax = axes[2]
    if vhot_rows:
        xs = np.array([r["committed"] for r in vhot_rows])
        ys = np.array([r["mine"] for r in vhot_rows])
        ax.scatter(xs, ys, s=8, alpha=0.6, color="#1a6faf")
        lim = [0, max(xs.max(), ys.max()) * 1.05]
        ax.plot(lim, lim, "k--", lw=0.8)
        ax.set_xlabel("e240 committed vhot (L1 share)")
        ax.set_ylabel("e254 reproduced vhot")
        dmax = float(np.abs(xs - ys).max())
        ax.set_title(f"G_VHOT: n={len(xs)} values, max |d| {dmax:.1e}",
                     fontsize=9.5)
    ax.grid(alpha=0.25)
    ax = axes[3]
    if gram_dev_rows:
        w0 = gram_dev_rows[0]["wash"]
        rows = [r for r in gram_dev_rows if r["wash"] == w0]
        xx = np.array([r["i"] for r in rows])
        ax.plot(xx, [r["committed"] for r in rows], "o-", ms=4, lw=1.4,
                color="#8e44ad", label="e234 committed spectrum")
        ax.plot(xx, [r["regen"] for r in rows], "s--", ms=4, lw=1.2,
                color="#e67e22", label="e254 regenerated (fp16 tier)")
        ax.set_yscale("log")
        ax.set_xlabel("eigenvalue rank (first-half Gram, %s)" % w0)
        ax.set_ylabel("eigenvalue")
        ax.set_title("G_BASIS/G_GRAM: the basis re-derivation", fontsize=9.5)
        ax.legend(fontsize=7.5)
    ax.grid(alpha=0.25, which="both")
    fig.suptitle("E254 — THE APPROXIMATION STACK DISCLOSED AND VALIDATED "
                 "(e240's gates re-run; the basis re-derived from the "
                 "committed Gram; the cache re-derived from the replay)",
                 fontsize=10)
    fig.tight_layout(rect=(0, 0, 1, 0.9))
    png = rd / f"{NAME}_validation.png"
    fig.savefig(png, dpi=130)
    plt.close(fig)
    return png


# ------------------------------------------------------------ main

RD = None

def main():
    global RD
    rd = run_dir(NAME)
    RD = rd
    jp = rd / "journal.json"
    log(f"E254 — THE V-SPAN OVERLAP (smoke={SMOKE}) -> {rd}")

    metrics = {
        "experiment": "e254_vspan_overlap",
        "phase": "v_t reconstructed by e240's fp64 recursion over the "
                 "certified wash replays; v's mass read on e234's "
                 "committed wash-span basis vs matched random subspaces; "
                 "the fact-hot + supply-echo co-reads; e240's validation "
                 "stack re-run",
        "date": now_iso(),
        "status": "PARTIAL: startup",
        "registration": REGISTERED["registration"],
        "registered_prediction": REGISTERED,
        "question": REGISTERED["question_verbatim"],
        "builds_on": [
            "the dispatch brief (FQ12 — the R64 ideator's Rank 1; "
            "scratch/review_r64_ideator.md)",
            "T226 / e246 (the anti-substrate: ALIGNED installs express "
            "nothing, ORTHO lands; H-i/H-ii; the registered "
            "rank-matched-random discriminator)",
            "T225 / e240 (the amplifier; v's mass on the LIVING hot sets; "
            "the fp64 v-reconstruction machinery, module-imported)",
            "T217 / e234 (the committed wash-span bases; the certified "
            "gradient caches' provenance; the split-half conventions)",
            "T198 / e226 (the support bank, the cache conventions, the "
            "hot-set ladder)",
            "e233 (the C-arm applied-step ledger), e182c/e182c2/e217 (the "
            "three-wash archive + certified draw streams)",
        ],
        "whats_new": [
            "the first read of the optimizer's SECOND MOMENT against the "
            "wash-span basis (the direction-level v-map, projection "
            "energy, k-ladder)",
            "the matched random-subspace null for moment mass (fresh "
            "gaussian draws, Gram-inverse exact projection, disclosed "
            "seeds)",
            "the supply-reference curves (the instantaneous g_t^2's span "
            "mass + the gradient-energy flavor from the committed Gram) "
            "— the amplifier texture at the span level",
            "the fact-hot coordinate companion (e240's vhot convention "
            "reproduced AND re-validated against e240's committed "
            "numbers)",
            "e240's full validation stack re-run on this cell's "
            "reconstruction (G_MOMENT/G_STEP/G_CE/G_DRAWS/G_REPLAY/"
            "G_E233/G_VHOT)",
        ],
        "smoke": SMOKE,
    }

    def write_metrics(status):
        metrics["status"] = status
        metrics["timing"] = {"total_s": round(time.time() - T0, 1)}
        save_json(rd / "metrics.json", metrics)

    journal: dict = {}
    if jp.exists():
        try:
            journal = json.loads(jp.read_text(encoding="utf-8"))
            log(f"journal restored: {list(journal)}")
        except Exception as e:                              # noqa: BLE001
            log(f"journal unreadable ({e}); starting fresh")
            journal = {}

    load_checks: list[dict] = [cpu_load_check("launch")]
    metrics["load_checks"] = load_checks
    ram_waits: list[dict] = []

    # ------------------------------------------------ P0 the committed records
    for p in (E226_M, E233_M, E234_M, E234_J, E240_M, E240_J):
        if not p.exists():
            log(f"FATAL: committed record missing: {p}")
            return 1
    e226m = json.loads(E226_M.read_text(encoding="utf-8"))
    e233m = json.loads(E233_M.read_text(encoding="utf-8"))
    e234m = json.loads(E234_M.read_text(encoding="utf-8"))
    e234j = json.loads(E234_J.read_text(encoding="utf-8"))
    e240m = json.loads(E240_M.read_text(encoding="utf-8"))
    e240j = json.loads(E240_J.read_text(encoding="utf-8"))
    e233_ledger = e233m.get("ledgers", {}).get("C")
    metrics["provenance_records"] = {
        "span_bases+gram": str(E234_J),
        "e234_metrics": str(E234_M),
        "v_reconstruction_machinery": "lab/e240_moment_archive.py "
                                      "(module-import)",
        "e240_validation_targets": {"metrics": str(E240_M),
                                    "journal": str(E240_J)},
        "e240_committed_validation": {
            "G_STEP_max_rel": e240m["gates"]["G_STEP"]
            ["max_rel_dev_rec_vs_live"],
            "G_MOMENT_max_rel_v": e240m["gates"]["G_MOMENT"]["max_rel_v"]},
        "supports+alignments": str(E226_M),
        "applied_steps_validation": str(E233_M),
        "washes": "runs/e182c (w1), runs/e182c2 (w2), runs/e217 (w3)",
    }

    # ------------------------------------------------ P1 organism + batteries
    tok, net0, org_meta = e1.load_organism()
    metrics["organism"] = {**org_meta, "torch_threads": 8}
    G_SIZE = {"params": org_meta["params"], "ceiling": e1.SIZE_CEILING,
              "reason": e1.SIZE_REASON,
              "pass": bool(org_meta["params"] <= e1.SIZE_CEILING)}
    assert G_SIZE["pass"]
    metrics["size_gate"] = G_SIZE

    bats, train_ids, G_CORPUS = e240.build_batteries(net0, tok)
    metrics["gates"] = {"G_SIZE": G_SIZE, "G_CORPUS": G_CORPUS}
    log("G_CORPUS: " + ("PASS" if G_CORPUS["pass"] else "FAIL"))
    assert G_CORPUS["pass"] or SMOKE
    write_metrics("PARTIAL: organism + corpus certified")

    p1m = json.loads((common.REPO / "runs" / "e182c" / "metrics.json")
                     .read_text(encoding="utf-8"))
    c2m = json.loads((common.REPO / "runs" / "e182c2" / "metrics.json")
                     .read_text(encoding="utf-8"))
    w1_rec = {s["step"]: s for s in p1m["states"]}
    w1_tmpl_rec = {s["step"]: s for s in c2m["part1_template"]["states"]}
    e216m = json.loads((common.REPO / "runs" / "e216" / "metrics.json")
                       .read_text(encoding="utf-8"))
    e216_rows = {r["fact"]: r for r in e216m["residual"]["table"]}

    def _probes(state_rec, batt):
        return {f: v["p"] for f, v in state_rec[batt]["probes"].items()}
    G_BATT = {}
    for b, bl in bats.items():
        mine_p = {r["fact"]: r["p"] for r in bl}
        ref1 = _probes(w1_rec[0], b) if b != "tmpl" \
            else _probes(w1_tmpl_rec[0], "tmpl")
        G_BATT[b] = {"n": len(bl),
                     "set_equal_committed": bool(set(mine_p) == set(ref1)),
                     "max_dp_w1": max(abs(mine_p[f] - v)
                                      for f, v in ref1.items())}
    G_BATT["pass"] = bool(all(G_BATT[b]["set_equal_committed"]
                              and G_BATT[b]["max_dp_w1"] <= 0.010
                              for b in bats)) or SMOKE
    metrics["gates"]["G_BATT"] = G_BATT
    log("G_BATT: " + ("PASS" if G_BATT["pass"] else "FAIL"))
    if not G_BATT["pass"]:
        write_metrics("PARTIAL: G_BATT FAILED — halted")
        return 1

    probes54: list[dict] = []
    for b in ("fact", "ctrl", "near", "tmpl"):
        for r in bats[b]:
            probes54.append({**r, "battery": b,
                             "family6": e216_rows[r["fact"]]["family6"]})
    assert len(probes54) == 54
    N_PARAMS = sum(p.numel() for p in net0.parameters())

    # ------------------------------------------------ P2 the supports bank
    load_checks.append(cpu_load_check("supports build"))
    ram_waits.append(ram_wait(RAM_FLOOR_GB, "supports memmap"))
    metrics["ram_waits"] = ram_waits
    e240.SCRATCH = SCRATCH           # this cell's scratch (e240's is free)
    sup = e240.build_supports(net0, probes54, 54, N_PARAMS, journal)
    G_SUPPORT = e240.certify_supports(net0, train_ids, probes54, sup, e226m)
    metrics["gates"]["G_SUPPORT"] = G_SUPPORT
    log(f"G_SUPPORT: fd {G_SUPPORT['fd_pass_n']}/54; probe-0 self-cos "
        f"{G_SUPPORT['determinism_selfcos_probe0']:.6f}; max dp vs e226 "
        f"{G_SUPPORT['max_dp_vs_e226_committed_w1s0_alignment']:.5f} -> "
        f"{'PASS' if G_SUPPORT['pass'] else 'FAIL'}")
    if not G_SUPPORT["pass"] and not SMOKE:
        write_metrics("PARTIAL: G_SUPPORT FAILED — halted")
        return 1
    # the fact battery's hot-coordinate unions (the ladder)
    fact_rows = [i for i, pr in enumerate(probes54)
                 if pr["battery"] == "fact"]
    fact_masks = {}
    for k_hot in K_LADDER_HOT:
        union = np.unique(np.concatenate(
            [sup["hot_idx"][(i, k_hot)] for i in fact_rows]))
        m = np.zeros(N_PARAMS, dtype=bool)
        m[union] = True
        fact_masks[k_hot] = m
    sup["probes54"] = probes54
    # the supports memmap is no longer needed — release (disclosed)
    try:
        sup["mm"].flush()
        sup["mm"]._mmap.close()
    except Exception:                                      # noqa: BLE001
        pass
    sup.pop("mm", None)
    (SCRATCH / "supports.npy").unlink(missing_ok=True)
    gc.collect()
    log("supports memmap released (hot sets extracted)")
    save_journal(rd, journal)
    write_metrics("PARTIAL: supports bank rebuilt + certified vs e226")

    # ------------------------------------------------ P3 the bases (committed)
    bases = {}
    for w in WASHES:
        Gs = np.array(e234j[f"gram_scaled_{w}"], dtype=np.float64)
        gn = np.array(e234j[w]["gnorms"], dtype=np.float64)
        Gn = true_gram(Gs, gn)
        k, cA, evec, ev, meta = basis_coeffs(Gn, HALF, KNEE_MAX_I, K_CAP)
        bases[w] = {"Gn": Gn, "gnorms": gn, "kA": k, "evec": evec,
                    "evals": ev, "meta": meta,
                    "cov_med": coverage_median(Gn, gn, cA, HALF)}
        log(f"basis {w}: knee k={k}, var_frac@k "
            f"{meta['var_frac_at_k']:.4f}, coverage median "
            f"{bases[w]['cov_med']:.5f}")

    # G_BASIS: the committed-data re-derivation vs e234's committed numbers
    G_BASIS = {"per_wash": {}, "tol_rel_spectrum": 1e-9,
               "tol_abs_coverage": 1e-9}
    gb_ok = not SMOKE
    for w in WASHES:
        if SMOKE:
            break
        committed = e234m["decomposition"][w]
        spec_c = np.array(committed["metaA"]["spectrum"], dtype=np.float64)
        spec_m = np.array(bases[w]["evals"][:len(spec_c)])
        rel = float(np.abs(spec_m - spec_c).max() / spec_c.max())
        cov_d = abs(bases[w]["cov_med"] - committed["coverage_A"]["median"])
        knee_ok = bases[w]["kA"] == committed["kA"]
        G_BASIS["per_wash"][w] = {
            "max_rel_spectrum_dev": rel, "knee_matches": knee_ok,
            "knee": bases[w]["kA"], "committed_knee": committed["kA"],
            "abs_coverage_dev": cov_d,
            "var_frac_at_k": bases[w]["meta"]["var_frac_at_k"],
            "committed_var_frac": committed["metaA"]["var_frac_at_k"]}
        gb_ok = gb_ok and rel <= 1e-9 and knee_ok and cov_d <= 1e-9
    G_BASIS["pass"] = bool(gb_ok) or SMOKE
    metrics["gates"]["G_BASIS"] = G_BASIS
    log("G_BASIS: " + ("PASS" if G_BASIS["pass"] else "FAIL"))
    write_metrics("PARTIAL: committed bases re-derived + certified")

    # the coefficient ladder per wash + the gradient-energy flavor (all t)
    cA_ladders = {w: ladder_from(bases[w]["evec"], bases[w]["evals"])
                  for w in WASHES}
    grad_energy = {}
    for w in WASHES:
        Gn, cA2 = bases[w]["Gn"], cA_ladders[w][K_PRIMARY]
        ge = []
        for t in range(1, min(STEPS, Gn.shape[0]) + 1):
            col = Gn[:HALF, t - 1]
            proj = cA2.T @ col
            ge.append(float(proj @ proj / Gn[t - 1, t - 1]))
        grad_energy[w] = ge

    # ------------------------------------------------ P4 the replays + reads
    stash_states = set(CURVE_GRID)
    all_tables = []
    curve_records = []
    gram_dev_rows = []
    vhot_rows = []
    snaps_by_wash, norms_by_wash = {}, {}
    wash_outputs = {}

    for w in WASHES:
        load_checks.append(cpu_load_check(f"replay {w}"))
        ram_waits.append(ram_wait(RAM_FLOOR_GB, f"grads memmap {w}"))
        metrics["ram_waits"] = ram_waits
        snap_states = set(ARCH_STATES[w]) | (
            set(CURVE_GRID) if w == PRIMARY_WASH else set())
        e234_wj = e234j.get(w) if not SMOKE else None
        out = replay_wash(net0, train_ids, sup, journal, w, e234_wj,
                          snap_states, stash_states)
        wash_outputs[w] = out
        write_metrics(f"PARTIAL: replay {w} done (gen_ok {out['gen_ok']})")
        gm = out["gm"]
        gnorms_mine = np.array([journal[w]["steps"][str(t)]["gnorm_raw"]
                                for t in range(1, HALF + 1)])

        # ---- G_GRAM: the regenerated Gram vs the committed one
        G_regen = gram_from_memmap(gm)
        Gn_mine = true_gram(G_regen, gnorms_mine)
        k_r, _cAr, evec_r, evr, _mr = basis_coeffs(
            Gn_mine, HALF, KNEE_MAX_I, K_CAP)
        if not SMOKE:
            Gs_c = np.array(e234j[f"gram_scaled_{w}"], dtype=np.float64)
            scale = float(CACHE_SCALE ** 2)
            dcos = float(np.abs(G_regen / scale
                                - Gs_c[:HALF, :HALF] / scale).max())
            n_cmp = min(20, len(evr), len(bases[w]["evals"]))
            eig_rel = float(np.abs(
                np.array(evr[:n_cmp])
                - np.array(bases[w]["evals"][:n_cmp])).max()
                / bases[w]["evals"][0])
            for i in range(n_cmp):
                gram_dev_rows.append({"i": i + 1, "wash": w,
                                      "committed":
                                          float(bases[w]["evals"][i]),
                                      "regen": float(evr[i])})
            ggram = {"max_abs_dcos": dcos, "tol_dcos": 2e-3,
                     "regen_knee": int(k_r),
                     "committed_knee": int(bases[w]["kA"]),
                     "max_rel_eig_dev_top20": eig_rel, "tol_eig": 0.01}
            ggram["pass"] = bool(dcos <= 2e-3 and k_r == bases[w]["kA"]
                                 and eig_rel <= 0.01)
            metrics["gates"].setdefault("G_GRAM", {})[w] = ggram
            log(f"G_GRAM {w}: dcos {dcos:.2e}, knee {k_r} vs "
                f"{bases[w]['kA']}, eig rel {eig_rel:.2e} -> "
                f"{'PASS' if ggram['pass'] else 'FAIL'}")
        else:
            # SMOKE: the pipeline's own self-consistent small basis
            bases[w].update({"kA": k_r, "evec": evec_r, "evals": evr})
            cA_ladders[w] = ladder_from(evec_r, evr)
            log(f"SMOKE basis {w}: regen knee {k_r}")

        # ---- G_VHOT: the vhot reproduction vs e240's committed journal
        if not SMOKE:
            dv, n_cmp2 = 0.0, 0
            for st, vh in out["vhot_mine"].items():
                ref = e240j[w]["arch_reads"][st]["vhot_share"]
                for fact, mine_k in vh.items():
                    for kk, val in mine_k.items():
                        dv = max(dv, abs(val - ref[fact][kk]))
                        n_cmp2 += 1
                        if kk == "2000":
                            vhot_rows.append({"wash": w, "state": st,
                                              "fact": fact, "mine": val,
                                              "committed": ref[fact][kk]})
            metrics["gates"].setdefault("G_VHOT", {})[w] = {
                "max_abs_dev": dv, "n_values": n_cmp2, "tol": 1e-8,
                "pass": bool(dv <= 1e-8)}
            log(f"G_VHOT {w}: max |dvhot| {dv:.2e} over {n_cmp2} values -> "
                f"{'PASS' if dv <= 1e-8 else 'FAIL'}")

        # ---- the span dots + masses for every snapshot of this wash
        snaps = out["snaps"]
        snaps_by_wash[w] = snaps
        norms_by_wash[w] = out["snap_norms"]
        lad = cA_ladders[w]
        for st in sorted(snaps):
            gdotv = dots_vs_cache(gm, gnorms_mine, snaps[st])
            masses = span_masses(gdotv, out["snap_norms"][st], lad)
            journal[w].setdefault("span_masses", {})[str(st)] = \
                {str(k): val for k, val in masses.items()}
            if st in out["snaps2"]:                      # raw flavor
                gd2r = dots_vs_cache(gm, gnorms_mine, out["snaps2"][st])
                m2 = span_masses(gd2r, out["snap2_norms"][st], lad)
                journal[w].setdefault("span_masses2", {})[str(st)] = \
                    {str(k): val for k, val in m2.items()}
                del gd2r
            if w == PRIMARY_WASH and st in out["g_stash"] \
                    and out["g_stash"][st] is not None:
                g64 = out["g_stash"][st].double()
                g2 = g64 * g64
                gd2 = dots_vs_cache(gm, gnorms_mine, g2)
                m2s = span_masses(gd2, out["stash_norms"][st], lad)
                journal[w].setdefault("supply_sq", {})[str(st)] = \
                    {str(k): val for k, val in m2s.items()}
                del g64, g2, gd2
        save_journal(rd, journal)

        # ---- release this wash's grads memmap + stashes
        try:
            gm.flush()
            gm._mmap.close()
        except Exception:                                  # noqa: BLE001
            pass
        out.pop("gm", None)
        out.pop("g_stash", None)
        out.pop("snaps2", None)
        (SCRATCH / f"grads_{w}.npy").unlink(missing_ok=True)
        gc.collect()
        log(f"{w}: grads memmap + stashes released")
        write_metrics(f"PARTIAL: {w} span reads done")

    # ------------------------------------------------ P5 the null + tables
    load_checks.append(cpu_load_check("null sweep"))
    ram_waits.append(ram_wait(RAM_FLOOR_NULL_GB, "null sweep"))
    metrics["ram_waits"] = ram_waits
    states_by_wash = {w: list(ARCH_STATES[w]) for w in WASHES}
    null_draws = null_sweep(states_by_wash, snaps_by_wash, norms_by_wash,
                            N_PARAMS)

    for w in WASHES:
        for st in states_by_wash[w]:
            masses = journal[w]["span_masses"][str(st)]
            for k in K_LADDER:
                dr = null_draws[(w, st, k)]
                sm = masses[str(k)]
                all_tables.append({
                    "wash": w, "state": st, "k": k, "span_mass": sm,
                    "null_mean": float(dr.mean()),
                    "null_min": float(dr.min()),
                    "null_max": float(dr.max()),
                    "null_sd": float(dr.std(ddof=1)),
                    "enrichment": sm / float(dr.mean())
                    if dr.mean() > 0 else float("nan"),
                    "within_band": bool(sm <= dr.max()),
                    "raw_flavor_span_mass":
                        journal[w].get("span_masses2", {}).get(
                            str(st), {}).get(str(k))})
    save_journal(rd, journal)

    # the fact-hot read (per wash, archived states)
    fact_hot = {}
    for w in WASHES:
        fh = fact_hot_read({st: snaps_by_wash[w][st]
                            for st in states_by_wash[w]}, fact_masks)
        fact_hot[w] = {f"t{st}_k{kk}": v for (st, kk), v in fh.items()}
    # release the snapshots (all reads that need them are done)
    snaps_by_wash.clear()
    for w in WASHES:
        wash_outputs[w].pop("snaps", None)
    gc.collect()

    # the curve table (w1)
    for st in sorted(set(CURVE_GRID)):
        if str(st) not in journal[PRIMARY_WASH].get("span_masses", {}):
            continue
        near = min(states_by_wash[PRIMARY_WASH],
                   key=lambda s: abs(s - st))
        row_near = next(t for t in all_tables
                        if t["wash"] == PRIMARY_WASH
                        and t["state"] == near and t["k"] == K_PRIMARY)
        curve_records.append({
            "t": st,
            "span_mass": journal[PRIMARY_WASH]["span_masses"]
            [str(st)][str(K_PRIMARY)],
            "supply_sq": journal[PRIMARY_WASH].get("supply_sq", {})
            .get(str(st), {}).get(str(K_PRIMARY)),
            "grad_energy": grad_energy[PRIMARY_WASH][st - 1],
            "null_mean": row_near["null_mean"],
            "null_min": row_near["null_min"],
            "null_max": row_near["null_max"]})

    # the t=1 internal consistency check (v_1 is a pure rescaling of g_1^2)
    t1_check = None
    if any(c["t"] == 1 for c in curve_records):
        c1 = next(c for c in curve_records if c["t"] == 1)
        if c1["supply_sq"] is not None:
            t1_check = {"span_mass_v_at_t1": c1["span_mass"],
                        "supply_sq_at_t1": c1["supply_sq"],
                        "abs_dev": abs(c1["span_mass"]
                                       - c1["supply_sq"]),
                        "note": "v_1 = (1-b2)(clip*g_1)^2 — a pure "
                                "rescaling of g_1^2; the two curves must "
                                "coincide at t=1 (they do up to the fp32 "
                                "snapshot quantization)"}

    # ------------------------------------------------ P6 the gates summary
    G_DRAWS = {"per_wash": {w: wash_outputs[w]["gen_ok"] for w in WASHES},
               "pass": bool(all(wash_outputs[w]["gen_ok"] is not False
                                for w in WASHES)) or SMOKE}
    ce_dev = [wash_outputs[w]["ce_cert"] for w in WASHES]
    gn_dev = [wash_outputs[w]["gnorm_cert"] for w in WASHES]
    G_CE = {"max_abs_dce_per_wash": ce_dev,
            "max_abs_dgnorm_per_wash": gn_dev, "tol": 1e-6,
            "pass": bool(all(d is not None and d <= 1e-6 for d in ce_dev)
                         and all(d is not None and d <= 1e-6
                                 for d in gn_dev)) or SMOKE}
    G_REPLAY = {"per_wash": {w: wash_outputs[w]["replay_cert"]
                             for w in WASHES},
                "tol_abs": {"w1": 1e-3, "w2": 1e-2, "w3": 1e-2}}
    _gr_ok = True
    for w in WASHES:
        for st, rec in (wash_outputs[w]["replay_cert"] or {}).items():
            if isinstance(rec, dict) and "max_abs_dw" in rec:
                if rec["max_abs_dw"] > G_REPLAY["tol_abs"][w]:
                    _gr_ok = False
    G_REPLAY["pass"] = bool(_gr_ok) or SMOKE
    step_rels, mom_rels = [], {"m": [], "v": []}
    for w in WASHES:
        for t in range(1, STEPS + 1):
            row = journal[w]["steps"][str(t)]
            if row["applied_norm_live"] > 0:
                step_rels.append(abs(row["applied_norm_rec"]
                                     - row["applied_norm_live"])
                                 / row["applied_norm_live"])
        for st, rc in (wash_outputs[w]["moment_certs"] or {}).items():
            mom_rels["m"].append(rc["rel_m_max"])
            mom_rels["v"].append(rc["rel_v_max"])
    G_STEP = {"max_rel_dev_rec_vs_live": float(max(step_rels, default=0.0)),
              "tol": 1e-3,
              "pass": bool(max(step_rels, default=0.0) <= 1e-3) or SMOKE}
    G_MOMENT = {"max_rel_m": float(max(mom_rels["m"], default=0.0)),
                "max_rel_v": float(max(mom_rels["v"], default=0.0)),
                "tol": 1e-4,
                "pass": bool(max(mom_rels["m"], default=0.0) <= 1e-4
                             and max(mom_rels["v"], default=0.0) <= 1e-4
                             ) or SMOKE}
    e233_vals = {"max_rel_dev": None, "median_rel_dev": None,
                 "spearman": None}
    if not SMOKE and e233_ledger is not None:
        mine = np.array([journal["w1"]["steps"][str(t)]
                         ["applied_norm_rec"] for t in range(1, STEPS + 1)])
        theirs = np.array([e233_ledger[str(t)]["applied_norm"]
                           for t in range(1, STEPS + 1)])
        rel = np.abs(mine - theirs) / theirs
        e233_vals = {"max_rel_dev": float(rel.max()),
                     "median_rel_dev": float(np.median(rel)),
                     "spearman": float(spearmanr(mine, theirs).statistic)}
    G_E233 = {**e233_vals,
              "pass": bool(e233_vals["spearman"] is not None
                           and e233_vals["spearman"] >= 0.99
                           and e233_vals["median_rel_dev"] <= 0.02
                           and e233_vals["max_rel_dev"] <= 0.05) or SMOKE}
    gv = metrics["gates"].get("G_VHOT", {})
    G_VHOT = {"per_wash": gv,
              "pass": bool(gv and all(gv[w]["pass"] for w in gv))}
    gg = metrics["gates"].get("G_GRAM", {})
    G_GRAM = {"per_wash": gg,
              "pass": bool(gg and all(gg[w]["pass"] for w in gg))}
    metrics["gates"].update({"G_DRAWS": G_DRAWS, "G_CE": G_CE,
                             "G_REPLAY": G_REPLAY, "G_STEP": G_STEP,
                             "G_MOMENT": G_MOMENT, "G_E233": G_E233,
                             "G_VHOT": G_VHOT, "G_GRAM": G_GRAM})
    log(f"G_DRAWS {G_DRAWS['per_wash']} | G_CE {ce_dev} | "
        f"G_STEP {G_STEP['max_rel_dev_rec_vs_live']:.2e} | "
        f"G_MOMENT v {G_MOMENT['max_rel_v']:.2e}")

    # ------------------------------------------------ P7 the adjudication
    primary_rows = [t for t in all_tables
                    if t["wash"] == PRIMARY_WASH and t["k"] == K_PRIMARY]
    enr = [t["enrichment"] for t in primary_rows]
    n_expected = len(ARCH_STATES[PRIMARY_WASH])
    b_enriched = bool(len(primary_rows) == n_expected
                      and all(e >= 3.0 for e in enr))
    b_flat = bool(len(primary_rows) == n_expected
                  and all(t["within_band"] for t in primary_rows))
    verdict = ("V-ENRICHED" if b_enriched else
               ("V-FLAT" if b_flat else "MIXED"))
    per_wash_verdicts = {}
    for w in [x for x in WASHES if x != PRIMARY_WASH]:
        rr = [t for t in all_tables if t["wash"] == w and t["k"] == 2]
        if rr:
            per_wash_verdicts[w] = {
                "min_enrichment": float(min(t["enrichment"]
                                             for t in rr)),
                "all_within_band": bool(all(t["within_band"] for t in rr)),
                "enriched_form": bool(all(t["enrichment"] >= 3.0
                                           for t in rr))}

    verdict_line = (
        f"{verdict} — w1 k=2 enrichment per state: "
        + ", ".join(f"t{t['state']} {t['enrichment']:.3g}"
                    for t in primary_rows)
        + (f"; span_mass {primary_rows[-1]['span_mass']:.4f} at t=80 vs "
           f"null mean {primary_rows[-1]['null_mean']:.3g}"
           if primary_rows else ""))

    metrics["reads"] = {
        "primary_definition": "span v-mass = ||P_k v_t||^2/||v_t||^2 "
        "(squared-L2 projection energy fraction onto the committed top-k "
        "first-half basis); null = 20 fresh gaussian-subspace draws "
        "(Gram-inverse exact projection); enrichment = span/null_mean",
        "tables": all_tables,
        "primary_rows": primary_rows,
        "curve_w1": curve_records,
        "t1_consistency_check": t1_check,
        "grad_energy_flavor": {w: grad_energy[w] for w in WASHES},
        "fact_hot": fact_hot,
        "null_meta": {"n_draws": N_NULL_DRAWS, "k_max": K_NULL_MAX,
                      "seed_base": NULL_SEED_BASE,
                      "seed_stride": NULL_SEED_STRIDE,
                      "chunk_stride": NULL_CHUNK_STRIDE,
                      "chunk": CHUNK_NULL,
                      "method": "fresh gaussian vectors (fp32 gen, fp64 "
                      "algebra), orthonormalized in closed form via the "
                      "Gram inverse (exact projection, nothing "
                      "materialized)"},
        "bases": {w: {"kA": bases[w]["kA"],
                      "var_frac_at_k": bases[w]["meta"]["var_frac_at_k"],
                      "coverage_median": bases[w]["cov_med"],
                      "spectrum_head": [float(x) for x in
                                        bases[w]["evals"][:10]]}
                  for w in WASHES},
        "t0_vmap": {
            "v_at_t0": 0.0,
            "disclosure": "the wash starts from a FRESH optimizer state — "
            "v_0 = 0 exactly; the pretraining's v is NOT reconstructable "
            "and is NOT in the wash's v at any state; the curve reads the "
            "wash's own history only"},
    }
    metrics["adjudication"] = {
        "verdict": (verdict + " (SMOKE — not adjudicated)") if SMOKE
        else verdict,
        "bars_verbatim": REGISTERED["bars_verbatim"],
        "booleans": {
            "v_enriched_all_states_ge_3x": b_enriched,
            "v_flat_all_states_within_band": b_flat,
            "primary_state_count": len(primary_rows),
            "min_enrichment_w1_k2": float(min(enr)) if enr else None},
        "operationalization": "sustained := enrichment >= 3 at EVERY w1 "
        "archived state {2,10,50,80}, k = the committed knee (2); within "
        "the band := span_mass <= the draws' max at every state",
        "per_wash_coreach": per_wash_verdicts,
        "gated_on": "G_SIZE/G_CORPUS/G_BATT/G_SUPPORT/G_CE/G_DRAWS/"
        "G_REPLAY/G_MOMENT/G_STEP/G_E233/G_VHOT/G_BASIS/G_GRAM",
        "all_gates_pass": bool(all(
            metrics["gates"][g].get("pass", False)
            for g in ("G_SIZE", "G_CORPUS", "G_BATT", "G_SUPPORT", "G_CE",
                      "G_DRAWS", "G_REPLAY", "G_MOMENT", "G_STEP",
                      "G_E233", "G_VHOT", "G_BASIS", "G_GRAM"))
        ) or SMOKE,
    }

    # ------------------------------------------------ P8 the plots
    pngs = []
    pngs.append(str(plot_enrichment(rd, all_tables, verdict_line)))
    pngs.append(str(plot_curve(rd, curve_records, verdict_line)))
    pngs.append(str(plot_validation(rd, journal, e233_ledger,
                                    gram_dev_rows, vhot_rows)))
    metrics["plot_outputs"] = pngs

    metrics["honesty_reflex"] = {
        "n": "1 organism (GPT-2 124M), 3 washes (w1 primary bit-exact; "
             "w2/w3 GPU-fp32-origin texture tier ~1.5e-3, disclosed); "
             "nothing guaranteed; the GRADED discipline applies",
        "instrument_risk_preannounced": "v is BUILT from the wash's own "
        "squared gradients and the span is BUILT from the wash's own "
        "gradients — a large enrichment vs the Haar-random null is "
        "arithmetically pre-announced; the registered bar speaks on the "
        "null alone and the supply references (the g_t^2 span mass + the "
        "gradient-energy flavor) + the fact-hot read carry the "
        "interpretation; no bar shopping",
        "reconstruction": "the v recursion is e240's, re-run with its "
        "validation stack (G_MOMENT/G_STEP vs the live optimizer; G_CE/"
        "G_DRAWS bit-exact vs e234's journal; G_E233 vs the committed GPU "
        "ledger; G_VHOT vs e240's committed vhot values)",
        "basis": "the span basis is e234's, re-derived from the COMMITTED "
        "Gram (G_BASIS machine-precision) and independently from the "
        "regenerated gradients (G_GRAM, fp16 cache tier)",
        "correlational": "the read is observational on reconstructed "
        "state; the CAUSAL tests are the registered rank-matched-random "
        "install cell (T226's discriminator) + the causal rider (a "
        "holder-hot-set install arm), both outside this cell",
        "mass_definition": "the primary is the direction-level projection "
        "energy; the per-coordinate companion (the fact-hot L1 read) "
        "answers Adam's per-coordinate mechanism in coordinate currency",
        "fp16_floor": "the gradient cache's fp16 dot floor ~5e-4/cos vs "
        "span masses ~0.1-0.5 and ratios ~1e6-1e8 — the floor is "
        "irrelevant to every registered number (disclosed)",
        "supports_t0_fixed": "the fact-hot sets are t=0-fixed (e226/e239 "
        "rotation disclosure)",
    }
    metrics["trims"] = []
    metrics["deviations"] = deviations
    metrics["compute"] = {"wall_s": round(time.time() - T0, 1),
                          "device": "CPU only", "threads": 8,
                          "load_checks": len(load_checks)}
    metrics["ram_waits"] = ram_waits

    metrics["status"] = "DONE (SMOKE — nothing adjudicated)" if SMOKE \
        else "DONE"
    write_metrics(metrics["status"])
    save_journal(rd, journal)
    if not SMOKE:
        import shutil
        shutil.rmtree(SCRATCH, ignore_errors=True)
        log(f"scratch cache deleted on DONE: {SCRATCH}")
    log(f"E254 {metrics['status']} — verdict {verdict}; "
        f"wall {time.time() - T0:.0f}s")
    return 0


if __name__ == "__main__":
    sys.exit(main())
